# WARNING - Generated by {fusen} from dev/flat_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("c2p_nest builds every combination with renamed value columns", {
  res <- c2p_nest(iris, cols = 1:3, by = "Species")
  expect_equal(nrow(res), 3L * 3L)
  expect_identical(names(res), c("pairs", "Species", "data"))
  expect_true(all(c("value1", "value2") %in% names(res$data[[1]])))
  expect_false("Species" %in% names(res$data[[1]]))
})

test_that("c2p_nest never renames columns of the input data.table", {
  dt <- data.table::as.data.table(iris)
  before <- data.table::copy(names(dt))
  c2p_nest(dt, cols = 1:3)
  expect_identical(names(dt), before)
})

test_that("c2p_nest validates its arguments", {
  expect_warning(c2p_nest(iris, cols = c(1, 1, 2)), "duplicated")
  df <- data.frame(a = 1, b = 2, value1 = 3)
  expect_error(c2p_nest(df, cols = c("a", "b")), "reserved")
  expect_error(c2p_nest(iris, cols = 1:2, pairs_n = 3), "cannot exceed")
})
