# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand # nolint: line_length_linter.

make_xlsx <- function() {
  d1 <- file.path(tempdir(), "xl_a"); d2 <- file.path(tempdir(), "xl_b")
  dir.create(d1, showWarnings = FALSE); dir.create(d2, showWarnings = FALSE)
  f <- c(file.path(d1, "2024.xlsx"), file.path(d2, "2024.xlsx"))
  writexl::write_xlsx(list(s1 = data.frame(v = 1:2), s2 = data.frame(v = 3)), f[1])
  writexl::write_xlsx(list(s1 = data.frame(v = 9)), f[2])
  f
}

test_that("import_xlsx adds tracking columns and separates equal base names", {
  f <- make_xlsx(); on.exit(unlink(dirname(f), recursive = TRUE))
  expect_warning(res <- import_xlsx(f), "same base name")
  expect_identical(names(res), c("excel_name", "sheet_name", "v"))
  expect_identical(unique(res$excel_name), c("2024", "2024_1"))
})

test_that("import_xlsx supports custom / omitted tracking columns", {
  f <- make_xlsx()[1]; on.exit(unlink(dirname(f), recursive = TRUE))
  res <- import_xlsx(f, file_col = NULL, sheet_col = "tab")
  expect_identical(names(res), c("tab", "v"))
})

test_that("import_xlsx reads empty sheets", {
  f <- tempfile(fileext = ".xlsx"); on.exit(unlink(f))
  writexl::write_xlsx(list(e = data.frame()), f)
  expect_equal(nrow(import_xlsx(f)), 0L)
})

test_that("import_xlsx parallel results are safe to modify by reference", {
  skip_on_cran()
  f <- make_xlsx(); on.exit(unlink(dirname(f), recursive = TRUE))
  res <- suppressWarnings(import_xlsx(f, combine = FALSE, workers = 2))
  expect_identical(names(res), c("2024_s1", "2024_s2", "2024_1_s1"))
  expect_silent(res[[1]][, z := 1])
  expect_true("z" %in% names(res[[1]]))
})

test_that(".combine_headers fills merged cells within their parent block", {
  h <- data.frame(a = c("ID", NA), b = c("Weight", "Start"), c = c(NA, "End"),
                  d = c("Backfat", "P2"), e = c(NA, "Loin"), f = c("Note\nfree", NA),
                  stringsAsFactors = FALSE)
  expect_identical(.combine_headers(h),
                   c("ID", "Weight_Start", "Weight_End", "Backfat_P2", "Backfat_Loin",
                     "Note free"))
  h3 <- data.frame(a = c("W", "D0", "kg"), b = c(NA, NA, "lb"), c = c(NA, "D21", "kg"),
                   stringsAsFactors = FALSE)
  expect_identical(.combine_headers(h3, sep = "."), c("W.D0.kg", "W.D0.lb", "W.D21.kg"))
  expect_identical(.combine_headers(data.frame(a = c(NA, NA), b = c("x", "x"))),
                   c("col_1", "x"))
})

test_that("import_xlsx reads multi-row headers and keeps column types", {
  f <- mintyr_example("multiheader_test.xlsx")
  res <- import_xlsx(f, skip = 1, header_rows = 2)
  expect_identical(names(res),
                   c("excel_name", "sheet_name", "ID", "Breed", "Birth date",
                     "Weight (kg)_Start", "Weight (kg)_End",
                     "Backfat (mm)_P2", "Backfat (mm)_Loin", "Note"))
  expect_equal(nrow(res), 7L)                          # blank spacer rows dropped
  expect_false(anyNA(res$ID))
  expect_type(res[["Weight (kg)_End"]], "double")
  expect_s3_class(res[["Birth date"]], "POSIXct")      # not "45296"
  one <- import_xlsx(f, sheet = "farm_B", skip = 1, header_rows = 2,
                     header_sep = ".", file_col = NULL, sheet_col = NULL)
  expect_identical(names(one)[4], "Weight (kg).Start")
  expect_equal(nrow(one), 3L)
})

test_that(".xlsx_merges reads merged ranges from the workbook", {
  f <- mintyr_example("multiheader_test.xlsx")
  m <- .xlsx_merges(f, "farm_B")
  expect_identical(colnames(m), c("r1", "c1", "r2", "c2"))
  expect_true(all(c("2-4-2-5", "2-1-3-1") %in% apply(m, 1, paste, collapse = "-")))
  g <- tempfile(fileext = ".xlsx"); on.exit(unlink(g))
  writexl::write_xlsx(iris[1:2, ], g)
  expect_equal(nrow(.xlsx_merges(g, "Sheet1")), 0L)
  expect_error(.xlsx_merges(f, "nope"), "not found")
})

test_that("merge information keeps genuinely empty header cells empty", {
  h <- data.frame(a = c("W", NA), b = c(NA, "End"), c = c(NA, "Note"))
  m <- cbind(r1 = 5L, c1 = 1L, r2 = 5L, c2 = 2L)        # only A5:B5 is merged
  expect_identical(.combine_headers(h, merges = m, first_row = 5L), c("W", "W_End", "Note"))
  expect_identical(.combine_headers(h), c("W", "W_End", "W_Note"))   # heuristic
  expect_identical(.combine_headers(h, fill = "none"), c("W", "End", "Note"))
  v <- data.frame(a = c("ID", NA, NA), b = c("x", "y", "z"))   # vertical merge A1:A3
  expect_identical(.combine_headers(v, merges = cbind(r1 = 1L, c1 = 1L, r2 = 3L, c2 = 1L)),
                   c("ID", "x_y_z"))
})

test_that("import_xlsx header_fill controls merged-cell handling", {
  f <- mintyr_example("multiheader_test.xlsx")
  last <- function(hf) utils::tail(names(import_xlsx(f, sheet = 1, skip = 1, header_rows = 2,
                                                    header_fill = hf)), 1L)
  expect_identical(last("auto"), "Note")
  expect_identical(last("right"), "Backfat (mm)_Note")
  expect_identical(last("none"), "Note")
  expect_error(import_xlsx(f, header_rows = 2, header_fill = "x"), "header_fill")
})

test_that("import_xlsx validates multi-row header arguments", {
  f <- mintyr_example("multiheader_test.xlsx")
  expect_error(import_xlsx(f, header_rows = 0), "header_rows")
  expect_error(import_xlsx(f, header_rows = 2, col_names = FALSE), "col_names")
  expect_error(import_xlsx(f, sheet = "nope"), "not found")
})

test_that("import_xlsx on_error controls failing files and sheets", {
  f <- mintyr_example("multiheader_test.xlsx")
  bad <- tempfile(fileext = ".xlsx"); on.exit(unlink(bad))
  writeLines("not a workbook", bad)
  expect_error(import_xlsx(c(f, bad)), "Failed to open 1 of 2")
  expect_warning(res <- import_xlsx(c(f, bad), skip = 1, header_rows = 2,
                                    on_error = "warn"), "skipped")
  expect_identical(unique(res$excel_name), "multiheader_test")
  expect_error(suppressWarnings(import_xlsx(bad, on_error = "warn")), "Failed to open")
  # sheet-level failure: col_types only fits one of two sheet layouts
  g <- tempfile(fileext = ".xlsx"); on.exit(unlink(g), add = TRUE)
  writexl::write_xlsx(list(ok = data.frame(a = 1, b = 2), bad = data.frame(a = 1)), g)
  expect_warning(res <- import_xlsx(g, on_error = "warn", col_types = c("numeric", "numeric")),
                 "sheet 'bad'")
  expect_identical(unique(res$sheet_name), "ok")
  expect_error(import_xlsx(g, col_types = c("numeric", "numeric")), "1 of 2 sheet")
})
