# WARNING - Generated by {fusen} from dev/flat_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("r2p_nest aligns records of the same id across levels", {
  d <- data.frame(id = c(1, 1, 2, 2), env = c("A", "B", "A", "B"),
                  t1 = 1:4, t2 = 5:8)
  res <- r2p_nest(d, names_from = "env", cols = c("t1", "t2"), id = "id")
  expect_identical(res$name, c("t1", "t2"))
  expect_identical(as.data.frame(res$data[[1]]),
                   data.frame(id = c(1, 2), A = c(1L, 3L), B = c(2L, 4L)))
  expect_s3_class(r2p_nest(d, "env", "t1", id = "id", out_type = "df")$data[[1]],
                  "data.frame", exact = TRUE)
})

test_that("r2p_nest refuses duplicated id / names_from combinations", {
  d <- data.frame(id = c(1, 1, 2), env = c("A", "A", "B"), t1 = 1:3)
  expect_error(r2p_nest(d, "env", "t1", id = "id"), "uniquely identify")
})
