# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Combine and Reshape Data by Specified Columns
#'
#' @description
#' Transforms a wide-format dataset into a nested data structure by combining 
#' specified columns and grouping by traits.
#'
#' @param data A data frame or data table containing the input data
#' @param cols2bind A single column name or index to use for binding/grouping
#' @param by A vector of column names or indices representing traits to be combined
#' @param nest_type The type of nested data structure to return. 
#'   Options are "dt" (data.table) or "df" (data frame). Defaults to "dt".
#'
#' @details
#' The function performs the following operations:
#' \itemize{
#'   \item Converts input to data.table format
#'   \item Validates input columns
#'   \item Reshapes data to long format using \code{melt()}
#'   \item Casts data to wide format using \code{dcast()}
#'   \item Creates a nested data structure grouped by traits
#' }
#'
#' @return A data.table with two columns:
#' \itemize{
#'   \item \code{trait}: The trait identifier
#'   \item \code{data}: A list column containing nested data structures
#' }
#'
#' @note
#' - Supports both numeric indices and column names for \code{cols2bind} and \code{by}
#' - Automatically detects and preserves ID columns
#' - Allows flexible reshaping of data with different nesting options
#' 
#' @importFrom data.table as.data.table melt dcast
#' @importFrom stats as.formula
#' @export
#' @examples
#' # Sample data
#' data <- data.frame(
#'   breed = c("A", "B", "A", "B"), 
#'   sex = c("F", "F", "M", "M"), 
#'   trait1 = c(1.1, 2.1, 3.5, 4.6),
#'   trait2 = c(5.2, 6.6, 7.3, 8.6))
#' # Method 1: Using combn_pair2() with data.table
#' # Combine by breed, grouping traits
#' combn_pair2(data, cols2bind = "breed", by = c("trait1", "trait2"))
#'
#' # Return as data frame nested structure
#' combn_pair2(data, cols2bind = "breed", 
#'                            by = c("trait1", "trait2"), 
#'                            nest_type = "df")
#' # Method 2: Using tidyr and dplyr for similar transformation
#' data |>
#'   tidyr::pivot_longer(cols = c("trait1", "trait2"), names_to = "name", values_to = "value") |>
#'   tidyr::pivot_wider(names_from = "breed", values_from = "value") |>
#'   dplyr::group_nest(name)

combn_pair2 <- function(data, cols2bind, by, nest_type = "dt") {# Type of nested data structure ("dt" or "df")
    . <- NULL
    # Ensure input is data.table format
    data <- as.data.table(data)
    
    # Validate and process cols2bind
    if (length(cols2bind) != 1) {
        stop("cols2bind must be a single column")
    }
    
    # Convert numeric indices to column names
    if (is.numeric(by)) {
        if (any(by > ncol(data) | by < 1)) {
            stop("Invalid column indices in by")
        }
        by <- names(data)[by]
    }
    
    if (is.numeric(cols2bind)) {
        if (cols2bind > ncol(data) | cols2bind < 1) {
            stop("Invalid column index in cols2bind")
        }
        cols2bind <- names(data)[cols2bind]
    }
    
    # Auto-detect ID columns (excluding trait columns)
    id_cols <- setdiff(names(data), by)
    
    # Parameter validation
    if (!all(by %in% names(data))) {
        stop("Specified by columns not found in data")
    }
    
    if (!cols2bind %in% names(data)) {
        stop("Specified cols2bind not found in data")
    }
    
    # 1. Reshape to long format
    long_dt <- melt(data,
                    id.vars = id_cols,
                    measure.vars = by,
                    variable.name = "trait",
                    value.name = "value")
    
    # 2. Reshape to wide format based on factor
    # Create formula for spreading data by factor
    other_ids <- setdiff(id_cols, cols2bind)
    formula_str <- paste(
        paste(c("trait", other_ids), collapse = " + "),
        cols2bind,
        sep = " ~ "
    )
    
    wide_dt <- dcast(long_dt,
                     as.formula(formula_str),
                     value.var = "value")
    
    # 3. Group by trait and create nested data structure based on nest_type
    if (nest_type == "dt") {
        result <- wide_dt[, .(data = list(.SD)), by = "trait"]
    }
    else if (nest_type == "df") {
        result <- wide_dt[, .(data = list(as.data.frame(.SD))), by = "trait"]
    }
    else {
        stop("Invalid nest_type provided. It must be either 'dt' or 'df'.")
    }
    
    return(result)
}
