# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Generate and Combine Column Pairs with Nested Data
#' 
#' @description
#' `combn_pair` generates combinations of specified columns, combines them, and nests the data.
#' It supports both data.table and data.frame inputs with optional grouping functionality.
#' 
#' @param data data.table or data.frame. The input dataset.
#' @param cols2bind character vector. Column names to be combined into pairs.
#' @param by character vector, optional. Column names for grouping. Default is NULL.
#' @param pairs_n integer, optional. Number of columns in each combination. 
#'        Must be >= 2 and <= length of cols2bind. Default is 2.
#' @param sep character, optional. Separator used when combining column names. Default is "-".
#' @param nest_type character, optional. Type of nested data to return: "dt" (data.table) or "df" (data.frame). Default is "dt".
#'
#' @return A nested data.table:
#' \itemize{
#'   \item When `by` is NULL: returns data.table nested by 'pairs'
#'   \item When `by` is specified: returns data.table nested by 'pairs' and grouping variables
#' }
#' 
#' @details
#' The function performs the following main steps:
#' 1. Validates input parameters
#' 2. Generates all possible combinations of specified columns
#' 3. Creates subsets for each combination and renames columns
#' 4. Merges all subsets and performs nesting
#'
#' @import data.table
#' @importFrom utils "combn"
#' 
#' @export
#' 
#' @note
#' Important considerations:
#' \itemize{
#'   \item cols2bind must be a character vector of existing column names
#'   \item pairs_n must be a positive integer >= 2 and <= number of columns in cols2bind
#'   \item sep must be a single character string
#'   \item Grouping variables in `by` must exist in the data
#'   \item nest_type must be either "dt" or "df"
#' }
#' @examples
#' col_names <- c("Sepal.Length", "Sepal.Width", "Petal.Length")
#' combn_pair(iris, cols2bind = col_names, pairs_n = 2, sep = "&")
#' combn_pair(iris, cols2bind = col_names, pairs_n = 2, by = "Species")
combn_pair <- function(data, cols2bind, by = NULL, pairs_n = 2, sep = "-", nest_type = "dt") {
  . <- pairs <- NULL  # For data.table's NSE
  
  # Validate inputs
  if (!inherits(data, c("data.table", "data.frame"))) {
    stop("data must be a data.table or a data.frame")
  }
  data <- data.table::as.data.table(data)
  
  if (!is.character(cols2bind)) {
    stop("cols2bind must be a character vector")
  }
  missing_cols <- cols2bind[!cols2bind %in% names(data)]
  if (length(missing_cols) > 0) {
    stop("Some columns specified in cols2bind are not present in the data: ", paste(missing_cols, collapse=", "))
  }
  
  # Validate pairs_n
  if (!is.numeric(pairs_n) || pairs_n < 2 || floor(pairs_n) != pairs_n) {
    stop("pairs_n must be a positive integer greater than or equal to 2")
  }
  
  # Check if pairs_n is less than or equal to the number of available columns
  if (pairs_n > length(cols2bind)) {
    stop(sprintf("pairs_n (%d) cannot be larger than the number of available columns (%d)", 
                 pairs_n, length(cols2bind)))
  }
  
  if (!is.character(sep) || length(sep) != 1) {
    stop("sep must be a single character string")
  }
  
  if (!is.null(by)) {
    if (!is.character(by)) {
      stop("'by' must be a character vector of column names.")
    }
    missing_by_vars <- by[!by %in% names(data)]
    if (length(missing_by_vars) > 0) {
      stop("Grouping variables not present in data: ", paste(missing_by_vars, collapse=", "))
    }
  }
  
  if (!nest_type %in% c("dt", "df")) {
    stop("Invalid nest_type provided. It must be either 'dt' or 'df'.")
  }
  
  # Prepare data for combination operations
  dt <- data.table::copy(data)  # Copy the data to avoid modifying the original
  
  fixed_cols <- setdiff(names(dt), cols2bind)
  comb_cols_list <- combn(cols2bind, pairs_n, simplify=FALSE)
  
  list_of_dts <- lapply(comb_cols_list, function(comb) {
    dt_subset <- dt[, c(fixed_cols, comb), with=FALSE]
    # Create pairs identifier
    pairs_name <- paste(comb, collapse=sep)
    # Rename the combination columns to 'value1', 'value2', etc.
    data.table::setnames(dt_subset, comb, paste0('value', seq_along(comb)))
    # Add 'pairs' column
    dt_subset[, pairs := pairs_name]
    dt_subset
  })
  
  dt_bind <- data.table::rbindlist(list_of_dts)
  
  # Determine grouping variables
  if (!is.null(by) && length(by) > 0) {
    groupby <- c("pairs", by)
  } else {
    groupby <- "pairs"
  }
  
  # Nest the data based on nest_type
  if (nest_type == "dt") {
    result <- dt_bind[, .(data = list(.SD)), by = groupby]
  } else if (nest_type == "df") {
    result <- dt_bind[, .(data = list(as.data.frame(.SD))), by = groupby]
  } else {
    stop("Invalid nest_type provided. It must be either 'dt' or 'df'.")
  }
  
  return(result)
}
