# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Convert Nested Columns Between `data.frame` and `data.table`
#'
#' @description
#' Transforms a `data.frame` or `data.table` by converting nested columns 
#' to either `data.frame` or `data.table` format while preserving the original data structure.
#'
#' @param data A `data.frame` or `data.table` containing nested columns
#' @param to A `character` string specifying the target format. 
#'   Options are `"df"` (data frame) or `"dt"` (data table). Defaults to `"df"`.
#' @param nest_cols A `character` vector of column names containing nested data. 
#'   If `NULL`, the function automatically detects list columns.
#'
#' @details
#' Advanced Nested Column Conversion Features:
#' \itemize{
#'   \item Intelligent automatic detection of nested columns
#'   \item Comprehensive conversion of entire data structure
#'   \item Selective conversion of specified nested columns
#'   \item Non-destructive transformation with data copying
#' }
#'
#' Conversion Strategies:
#' \enumerate{
#'   \item Nested column identification based on `is.list()` detection
#'   \item Preservation of original data integrity
#'   \item Flexible handling of mixed data structures
#'   \item Consistent type conversion across nested elements
#' }
#'
#' Nested Column Handling:
#' \itemize{
#'   \item Supports conversion of `list` columns
#'   \item Handles `data.table`, `data.frame`, and generic `list` inputs
#'   \item Maintains original column structure and order
#'   \item Prevents in-place modification of source data
#' }
#'
#' @return 
#' A transformed `data.frame` or `data.table` with nested columns converted to the specified format.
#'
#' @note
#' Conversion Characteristics:
#' \itemize{
#'   \item Non-destructive transformation of nested columns
#'   \item Supports flexible input and output formats
#'   \item Intelligent type detection and conversion
#'   \item Minimal performance overhead
#' }
#'
#' @seealso
#' \itemize{
#'   \item [`data.table::as.data.table()`]
#'   \item [`tibble::as_tibble()`]
#' }
#'
#' @importFrom data.table as.data.table copy
#' @importFrom tibble as_tibble
#' 
#' @export
#' @examples
#' # Convert a data frame with nested columns to data table
#' df_nest1 <- iris |> 
#'   dplyr::group_nest(Species)
#' df_nest1
#' df_nest2 <- iris |>
#'   dplyr::group_nest(Species) |>
#'   dplyr::mutate(data2 = purrr::map(data, dplyr::mutate, c=2))
#' df_nest2
#' # Convert a data table with specific nested columns to data frame
#' convert_nest(df_nest1, to = "dt", nest_cols = c("data"))
#' convert_nest(df_nest2, to = "dt", nest_cols = c("data", "data2"))
#' # Convert a data table with nested columns to data frame
#' dt_nest <- mintyr::w2l_nest(data = iris, cols2l = 1:2, by = "Species")
#' convert_nest(dt_nest, to = "df", nest_cols = c("data"))
convert_nest <- function(data, to = c("df", "dt"), nest_cols = NULL) {
  to <- match.arg(to)

  # Automatically detect nested columns (list columns) if not specified
  if (is.null(nest_cols)) {
    nest_cols <- names(data)[sapply(data, is.list)]
  }

  if (to == "df") {
    # If data is data.table, convert to data.frame and copy to avoid modifying original data
    if (inherits(data, "data.table")) {
      data <- as_tibble(copy(data))
    } else if (!inherits(data, "data.frame")) {
      data <- as_tibble(data)
    }
    # Convert each element of nested columns to data.frame
    for (col in nest_cols) {
      data[[col]] <- lapply(data[[col]], function(x) {
        if (inherits(x, "data.table")) {
          as_tibble(copy(x))
        } else if (!inherits(x, "data.frame")) {
          as_tibble(x)
        } else {
          x
        }
      })
    }
  } else if (to == "dt") {
    # If data is not data.table, convert to data.table and copy to avoid modifying original data
    if (!inherits(data, "data.table")) {
      data <- as.data.table(copy(data))
    }
    # Convert each element of nested columns to data.table
    for (col in nest_cols) {
      data[[col]] <- lapply(data[[col]], function(x) {
        if (!inherits(x, "data.table")) {
          as.data.table(copy(x))
        } else {
          x
        }
      })
    }
  }

  return(data)
}
