# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Convert Nested Columns Between Data Frame and Data Table
#'
#' @description
#' This function converts a data frame or data table, transforming nested columns 
#' to either data frame or data table format while preserving the original data structure.
#'
#' @param data A data frame or data table containing nested columns
#' @param to A character string specifying the target format. 
#'   Options are "df" (data frame) or "dt" (data table). Defaults to "df".
#' @param nested_cols A character vector of column names containing nested data. 
#'   If NULL, the function automatically detects list columns.
#'
#' @details
#' The function performs the following operations:
#' \itemize{
#'   \item Automatically detects nested columns if not explicitly specified
#'   \item Converts the entire data structure to the target format (data frame or data table)
#'   \item Converts nested columns within the specified columns to the target format
#'   \item Creates a copy of the input data to avoid modifying the original
#' }
#'
#' @return A data frame or data table with nested columns converted to the specified format
#'
#' @note
#' - The function preserves the original data structure
#' - Nested columns are converted individually
#' - Automatic detection of nested columns is based on list-type columns
#' 
#' @importFrom data.table as.data.table copy
#' @export
#' @examples
#' # Convert a data frame with nested columns to data table
#' df_nest1 <- iris |> 
#'   dplyr::group_nest(Species)
#' df_nest2 <- iris |>
#'   dplyr::group_nest(Species) |>
#'   dplyr::mutate(data2 = purrr::map(data, dplyr::mutate, c=2))
#' # Convert a data table with specific nested columns to data frame
#' convert_nested(df_nest1, to = "dt", nested_cols = c("data"))
#' convert_nested(df_nest2, to = "dt", nested_cols = c("data", "data2"))
#' # Convert a data table with nested columns to data frame
#' dt_nest <- mintyr::w2l_nest(data = iris, cols2l = 1:2, by = "Species")
#' convert_nested(dt_nest, to = "dt", nested_cols = c("data"))
convert_nested <- function(data, to = c("df", "dt"), nested_cols = NULL) {
  to <- match.arg(to)

  # Automatically detect nested columns (list columns) if not specified
  if (is.null(nested_cols)) {
    nested_cols <- names(data)[sapply(data, is.list)]
  }

  if (to == "df") {
    # If data is data.table, convert to data.frame and copy to avoid modifying original data
    if (inherits(data, "data.table")) {
      data <- as.data.frame(copy(data))
    } else if (!inherits(data, "data.frame")) {
      data <- as.data.frame(data)
    }
    # Convert each element of nested columns to data.frame
    for (col in nested_cols) {
      data[[col]] <- lapply(data[[col]], function(x) {
        if (inherits(x, "data.table")) {
          as.data.frame(copy(x))
        } else if (!inherits(x, "data.frame")) {
          as.data.frame(x)
        } else {
          x
        }
      })
    }
  } else if (to == "dt") {
    # If data is not data.table, convert to data.table and copy to avoid modifying original data
    if (!inherits(data, "data.table")) {
      data <- as.data.table(copy(data))
    }
    # Convert each element of nested columns to data.table
    for (col in nested_cols) {
      data[[col]] <- lapply(data[[col]], function(x) {
        if (!inherits(x, "data.table")) {
          as.data.table(copy(x))
        } else {
          x
        }
      })
    }
  }

  return(data)
}
