# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Export a List of Data Frames with Hierarchical Directory Management
#'
#' @description
#' Exports every element of a named (or unnamed) \code{list} of \code{data.frame} /
#' \code{data.table} objects to \code{txt} or \code{csv} files.  Element names may
#' contain forward-slashes (\code{/}) to encode arbitrary subdirectory depth, e.g.
#' \code{"group_a/subject_01/results"} writes
#' \code{<export_path>/group_a/subject_01/results.txt}.
#' Unnamed elements are automatically labelled \code{split_<i>}.
#'
#' @param split_dt    A non-empty \code{list} whose elements are \code{data.frame},
#'   \code{data.table}, or any object coercible via \code{data.table::as.data.table()}.
#' @param export_path Single character string - the root export directory.
#'   Created recursively if absent. Defaults to \code{tempdir()}.
#' @param file_type   \code{"txt"} (tab-separated, default) or \code{"csv"}
#'   (comma-separated). Case-insensitive.
#'
#' @return An invisible named \code{character} vector of the absolute file paths
#'   written, with length equal to the number of successfully exported elements.
#'   The total count is accessible via \code{length()} on the return value.
#'
#' @details
#' **Performance design:**
#' \itemize{
#'   \item All element names are resolved and path components split in a single
#'     vectorised pass \emph{before} the write loop, so no string work occurs
#'     inside the hot path.
#'   \item Unique subdirectories are collected and created in one batch
#'     (\code{k} \code{dir.create()} syscalls, where \code{k} \eqn{\le} \code{n}).
#'   \item The field separator is resolved once at function entry.
#'   \item \code{as.data.table()} on an existing \code{data.table} is a
#'     reference-pass (no copy).
#' }
#'
#' **Error handling:**
#' Individual element failures emit a \code{warning} and are skipped; the
#' remaining elements continue to be processed.
#'
#' @section Dependencies:
#' Requires the \pkg{data.table} package.
#'
#' @seealso \code{\link[data.table]{fwrite}}
#'
#' @importFrom data.table is.data.table as.data.table fwrite
#' @export
#' @examples
#' # Example: Export split data to files
#'
#' # Step 1: Create split data structure
#' dt_split <- w2l_split(
#'   data = iris,              # Input iris dataset
#'   cols2l = 1:2,             # Columns to be split
#'   by = "Species"            # Grouping variable
#' )
#'
#' # Step 2: Export split data to files
#' export_list(
#'   split_dt = dt_split       # Input list of data.tables
#' )
#' # Returns the number of files created
#' # Files are saved in tempdir() with .txt extension
#'
#' # Check exported files
#' list.files(
#'   path = tempdir(),         # Default export directory
#'   pattern = "txt",          # File type pattern to search
#'   recursive = TRUE          # Search in subdirectories
#' )
#'
#' # Clean up exported files
#' files <- list.files(
#'   path = tempdir(),         # Default export directory
#'   pattern = "txt",          # File type pattern to search
#'   recursive = TRUE,         # Search in subdirectories
#'   full.names = TRUE         # Return full file paths
#' )
#' file.remove(files)          # Remove all exported files
export_list <- function(split_dt,
                        export_path = tempdir(),
                        file_type   = "txt") {

  # -- 0. Dependency check -------------------------------------------------------
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required. Install with install.packages('data.table').")
  }

  # -- 1. Input validation (fail-fast) ------------------------------------------
  if (!is.list(split_dt)) {
    stop("'split_dt' must be a list of data.frame / data.table objects.")
  }
  if (length(split_dt) == 0L) {
    message("[ export_list ] 'split_dt' is empty - nothing to export.")
    return(invisible(character(0L)))
  }
  if (!is.character(export_path) || length(export_path) != 1L || is.na(export_path)) {
    stop("'export_path' must be a single non-NA character string.")
  }

  # Resolve separator once - never recompute inside the loop.
  file_type <- tolower(trimws(file_type))
  if (!file_type %in% c("txt", "csv")) {
    stop("'file_type' must be \"txt\" or \"csv\".")
  }
  sep <- if (file_type == "txt") "\t" else ","

  # -- 2. Vectorised name resolution ---------------------------------------------
  # Build a canonical character vector of element names in one pass.
  # Unnamed / empty-string elements fall back to "split_<i>".
  raw_names <- names(split_dt)
  elem_names <- vapply(
    seq_along(split_dt),
    function(i) {
      nm <- if (is.null(raw_names)) "" else raw_names[i]
      if (is.na(nm) || nchar(nm) == 0L) paste0("split_", i) else nm
    },
    FUN.VALUE = character(1L)
  )

  # -- 3. Vectorised path decomposition -----------------------------------------
  # Split every name on "/" once, outside the write loop.
  # Result: list of character vectors, one per element.
  path_parts <- strsplit(elem_names, "/", fixed = TRUE)

  # Derive the subdirectory and bare filename for each element.
  # file_names : character(n) - the last path component (no extension)
  # dir_paths  : character(n) - full absolute directory path
  n <- length(split_dt)

  file_names <- vapply(path_parts, function(p) p[length(p)],  FUN.VALUE = character(1L))
  sub_dirs   <- vapply(path_parts,
                       function(p) {
                         if (length(p) > 1L) paste(p[-length(p)], collapse = "/") else ""
                       },
                       FUN.VALUE = character(1L))

  dir_paths <- ifelse(
    nchar(sub_dirs) > 0L,
    file.path(export_path, sub_dirs),
    export_path
  )

  # -- 4. Batch directory creation -----------------------------------------------
  # Always ensure the root exists, then create every unique subdirectory in one
  # batch - k syscalls instead of n (k = number of unique directories, k <= n).
  all_dirs <- unique(c(export_path, dir_paths))
  lapply(all_dirs, dir.create, showWarnings = FALSE, recursive = TRUE)

  # -- 5. Pre-compute full file paths (once, before the write loop) --------------
  full_paths <- file.path(dir_paths, paste0(file_names, ".", file_type))

  # -- 6. Write loop -------------------------------------------------------------
  # - seq_len() avoids the 1:0 == c(1,0) edge case.
  # - Individual failures are caught and warned; processing continues.
  # - as.data.table() on an existing data.table is a zero-copy reference pass.
  # - Accumulate successfully written paths for the return value.
  written_paths <- character(n)   # Pre-allocate; trim after the loop.
  write_count   <- 0L

  for (i in seq_len(n)) {
    tryCatch({
      dt_elem <- data.table::as.data.table(split_dt[[i]])

      # Skip zero-row elements silently - nothing meaningful to write.
      if (nrow(dt_elem) == 0L) next

      data.table::fwrite(dt_elem, file = full_paths[i], sep = sep, quote = TRUE)

      write_count <- write_count + 1L
      written_paths[write_count] <- full_paths[i]

    }, error = function(e) {
      warning(sprintf("[ export_list ] Failed to export element %d ('%s'): %s",
                      i, elem_names[i], conditionMessage(e)),
              call. = FALSE)
    })
  }

  # Trim pre-allocated vector to actual written count.
  written_paths <- written_paths[seq_len(write_count)]
  names(written_paths) <- elem_names[match(written_paths, full_paths)]

  # -- 7. Summary ----------------------------------------------------------------
  message(sprintf("[ export_list ] Export complete. %d / %d file(s) written to: %s",
                  write_count, n, export_path))

  invisible(written_paths)
}
