# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Export Data to XLSX Files
#'
#' @description
#' The natural complement to \code{import_xlsx()}.  Accepts either a combined
#' \code{data.frame} (as produced by \code{import_xlsx()} with
#' \code{rbind = TRUE}) **or a named list of data.frames**, and writes the
#' result to disk.
#'
#' The output \strong{destination} is controlled by a single \code{path}
#' argument -- there are no separate modes to choose:
#'
#' \itemize{
#'   \item \strong{\code{path} is a directory} (no \code{.xlsx} extension) --
#'         write \emph{one \code{.xlsx} file per element} into that directory.
#'         Each file contains a single sheet named after the list element (or
#'         the \code{file_col} value for \code{data.frame} input).
#'   \item \strong{\code{path} is a file} (ends in \code{.xlsx}) -- write
#'         \emph{everything into a single workbook}, one sheet per list element
#'         (or per \code{sheet_col} / \code{file_col} value for
#'         \code{data.frame} input).
#' }
#'
#' \subsection{Named-list input}{
#'   Pass \code{data} as a named list of \code{data.frame}s:
#'
#'   \preformatted{res <- list(res1 = data1, res2 = data2, res3 = data3)
#'
#'   # Directory mode -- writes res1.xlsx, res2.xlsx, res3.xlsx
#'   export_xlsx(res, path = "output/")
#'
#'   # Single-file mode -- one workbook with sheets res1, res2, res3
#'   export_xlsx(res, path = "output/all.xlsx")}
#'
#'   List names must be non-empty and unique.  Each element must be a
#'   \code{data.frame}, \code{data.table}, or \code{tibble}.  Elements of
#'   different types may be mixed freely within the same list.
#' }
#'
#' @param data       A \code{data.frame} / \code{data.table} / \code{tibble},
#'                   \strong{or} a named list of such objects.  For list input,
#'                   names become file names (directory mode) or sheet names
#'                   (single-file mode).  Tracking columns
#'                   (\code{file_col} / \code{sheet_col}) are optional for
#'                   \code{data.frame} input.
#' @param path       \code{character(1)}.  Output destination.  A path ending
#'                   in \code{.xlsx} (case-insensitive) is treated as a
#'                   \strong{single workbook}; anything else is treated as an
#'                   \strong{output directory}.  Parent directories are created
#'                   recursively as needed.
#' @param file_col   \code{character(1)}.  Column identifying the source file
#'                   (used for \code{data.frame} input only).
#'                   Default \code{"excel_name"}.
#' @param sheet_col  \code{character(1)}.  Column identifying the source sheet
#'                   (used for \code{data.frame} input only).
#'                   Default \code{"sheet_name"}.
#' @param sheet_name \code{character(1)}.  Worksheet tab name for the
#'                   single-sheet fallback (plain \code{data.frame} with no
#'                   tracking columns).  Default \code{"Sheet1"}.
#' @param drop_cols  \code{logical(1)}.  When \code{TRUE} (default) the
#'                   tracking columns are stripped from every exported sheet.
#' @param overwrite  \code{logical(1)}.  Allow overwriting existing files.
#'                   Default \code{TRUE}.
#' @param verbose    \code{logical(1)}.  Print a message for every sheet/file
#'                   written.  Default \code{FALSE}.
#'
#' @details
#' \subsection{Why \pkg{writexl}?}{
#'   \pkg{writexl} writes \code{.xlsx} via a minimal C library with no Java or
#'   Perl dependency.  It is faster than \pkg{openxlsx} for plain export and
#'   produces smaller files, at the cost of no cell formatting, formulas, or
#'   styles.  For those, use \pkg{openxlsx} / \pkg{openxlsx2}.
#' }
#' \subsection{Sheet-name sanitisation}{
#'   Excel sheet names are limited to 31 characters and may not contain
#'   \code{[ ] * ? / \\ :}.  Both constraints are enforced automatically.
#' }
#' \subsection{Directory vs. file dispatch}{
#'   The single \code{path} argument is classified purely by its extension: a
#'   trailing \code{.xlsx} means "one workbook", anything else means "a
#'   directory of files".  If you want a directory whose name happens to end in
#'   \code{.xlsx}, append a trailing slash.
#' }
#'
#' @return Invisibly, a named \code{character} vector of written file paths.
#'   In directory mode the vector is named by list-element / \code{file_col}
#'   value; in single-workbook mode it is named by \code{path}.
#'
#' @importFrom data.table is.data.table as.data.table copy
#' @importFrom writexl write_xlsx
#' @export
#' @examples
#' # Example 1: Export a plain data.frame to a single workbook
#' out_file <- file.path(tempdir(), "test.xlsx")
#' export_xlsx(
#'   mtcars,                             # Data to export (no tracking columns)
#'   path       = out_file,              # Ends in .xlsx -> one workbook
#'   sheet_name = "mtcars"              # Worksheet tab name for the single sheet
#' )
#' file.remove(out_file)
#'
#' # Example 2: Export a data.table to a single workbook
#' # data.table input is handled identically to data.frame
#' out_file <- file.path(tempdir(), "test.xlsx")
#' hah <- data.table::as.data.table(mtcars)
#' export_xlsx(
#'   hah,                                # data.table input
#'   path       = out_file,              # Ends in .xlsx -> one workbook
#'   sheet_name = "mtcars"              # Worksheet tab name for the single sheet
#' )
#' file.remove(out_file)
#'
#' # Example 3: Split a data.frame into one sheet per group (single workbook)
#' # `iris` has a `Species` column; each species becomes a separate sheet tab
#' out_file <- file.path(tempdir(), "iris_by_species.xlsx")
#' export_xlsx(
#'   iris,                               # Data to export
#'   path      = out_file,              # Ends in .xlsx -> one workbook
#'   file_col  = "Species",             # Column whose unique values name each sheet
#'   drop_cols = FALSE                  # Keep the Species column in each sheet
#' )
#' file.remove(out_file)
#'
#' # Example 4: Split a data.table into one sheet per group (single workbook)
#' out_file <- file.path(tempdir(), "iris_by_species.xlsx")
#' haha <- data.table::as.data.table(iris)
#' export_xlsx(
#'   haha,                              # data.table input
#'   path      = out_file,              # Ends in .xlsx -> one workbook
#'   file_col  = "Species",             # Column whose unique values name each sheet
#'   drop_cols = FALSE                  # Keep the Species column in each sheet
#' )
#' file.remove(out_file)
#'
#' # Example 5: Split into one file per group (directory mode)
#' # Omit the .xlsx extension -> directory mode: one file per Species value
#' out_files <- export_xlsx(
#'   iris,                              # Data to export
#'   path      = tempdir(),             # A directory -> one file per file_col value
#'   file_col  = "Species",            # Column whose values name the output files
#'   drop_cols = FALSE                 # Keep the Species column in each output file
#' )
#' file.remove(out_files)
#'
#' # Example 6: Named list -> single workbook, one sheet per element
#' # List names (res1, res2) become the sheet tab names
#' out_file <- file.path(tempdir(), "combined.xlsx")
#' res <- list(res1 = iris, res2 = mtcars)
#' export_xlsx(
#'   res,                               # Named list of data.frames
#'   path    = out_file                 # Ends in .xlsx -> one workbook
#' )
#' file.remove(out_file)
#'
#' # Example 7: Named list -> directory, one file per element
#' # Omit the .xlsx extension -> one file per list element
#' res <- list(res1 = iris, res2 = mtcars)
#' out_files <- export_xlsx(
#'   res,                               # Named list of data.frames
#'   path    = tempdir()               # A directory -> res1.xlsx, res2.xlsx
#' )
#' file.remove(out_files)
export_xlsx <- function(data,
                        path,
                        file_col   = "excel_name",
                        sheet_col  = "sheet_name",
                        sheet_name = "Sheet1",
                        drop_cols  = TRUE,
                        overwrite  = TRUE,
                        verbose    = FALSE) {

  # -- 0. Named-list input -----------------------------------------------------
  #
  # list(res1 = data1, res2 = data2, res3 = data3)
  #
  # Each element must be a data.frame (or data.table / tibble).
  # Names become:
  #   * directory mode  -> individual file names  (<name>.xlsx)
  #   * single-file mode -> sheet names inside the workbook
  #
  # Implementation: the list is handled directly inside the dispatch block
  # (step 3) rather than being "unrolled" into a combined data.frame, which
  # avoids forcing every element to share an identical column set.

  is_named_list <- is.list(data) && !is.data.frame(data)

  if (is_named_list) {
    if (length(data) == 0L)
      stop("`data` is an empty list -- nothing to export.", call. = FALSE)

    nms <- names(data)
    if (is.null(nms) || any(!nzchar(nms)))
      stop("Every element of a list `data` must have a non-empty name.",
           call. = FALSE)
    if (anyDuplicated(nms))
      stop("List names must be unique (they become file / sheet names).",
           call. = FALSE)

    not_df <- !vapply(data, is.data.frame, logical(1L))   # data.table / tibble pass
    if (any(not_df))
      stop(sprintf(
        "All list elements must be a data.frame, data.table, or tibble.  Non-conforming element(s): %s",
        paste(nms[not_df], collapse = ", ")), call. = FALSE)
  }

  # -- 1. Input validation (data.frame path) ----------------------------------

  if (!is_named_list && !is.data.frame(data))
    stop("`data` must be a data.frame, data.table, tibble, or named list of data.frames.",
         call. = FALSE)

  if (!is.character(path) || length(path) != 1L || is.na(path) || !nzchar(path))
    stop("`path` must be a single non-empty character string.", call. = FALSE)

  if (!is.character(sheet_name) || length(sheet_name) != 1L ||
      is.na(sheet_name) || !nzchar(sheet_name))
    stop("`sheet_name` must be a single non-empty character string.", call. = FALSE)

  if (!is.logical(overwrite) || length(overwrite) != 1L || is.na(overwrite))
    stop("`overwrite` must be a single non-NA logical.", call. = FALSE)

  # Classify the destination: file (single workbook) vs directory.
  to_single_file <- grepl("\\.xlsx$", path, ignore.case = TRUE)

  # -- 2. Helpers -------------------------------------------------------------

  .safe_sheet <- function(x) {
    x <- gsub("[\\[\\]\\*\\?\\/\\\\:]", "_", x, perl = TRUE)
    substr(x, 1L, 31L)
  }

  .save <- function(sheet_list, file) {
    dir_path <- dirname(file)
    if (!dir.exists(dir_path)) dir.create(dir_path, recursive = TRUE)
    if (!overwrite && file.exists(file))
      stop(sprintf("File already exists (overwrite = FALSE): %s", file),
           call. = FALSE)
    writexl::write_xlsx(sheet_list, path = file)
    if (verbose) message(sprintf("Saved: %s", file))
  }

  # -- 3a. Named-list dispatch -------------------------------------------------

  if (is_named_list) {
    nms        <- names(data)
    safe_nms   <- vapply(nms, .safe_sheet, character(1L))

    if (to_single_file) {
      # One workbook, one sheet per list element.
      sheet_list <- stats::setNames(
        lapply(data, as.data.frame),
        safe_nms
      )
      if (verbose)
        for (nm in safe_nms)
          message(sprintf("  Sheet '%s': %d rows", nm, nrow(sheet_list[[nm]])))
      .save(sheet_list, path)
      return(invisible(stats::setNames(path, path)))

    } else {
      # Directory mode: one file per list element.
      if (!dir.exists(path)) dir.create(path, recursive = TRUE)
      out_paths <- file.path(path, paste0(nms, ".xlsx"))

      for (i in seq_along(data)) {
        df  <- as.data.frame(data[[i]])
        lbl <- safe_nms[[i]]
        if (verbose)
          message(sprintf("  Sheet '%s': %d rows", lbl, nrow(df)))
        .save(stats::setNames(list(df), lbl), out_paths[[i]])
      }
      return(invisible(stats::setNames(out_paths, nms)))
    }
  }

  # -- 3b. data.frame dispatch (original logic) -------------------------------

  data_df <- as.data.frame(data)
  data_dt <- if (data.table::is.data.table(data))
    data.table::copy(data)
  else
    data.table::as.data.table(data)

  has_file_col  <- file_col  %in% names(data_df)
  has_sheet_col <- sheet_col %in% names(data_df)

  .drop <- function(df) {
    if (!drop_cols) return(df)
    cols <- intersect(c(if (has_file_col) file_col, if (has_sheet_col) sheet_col),
                      names(df))
    if (length(cols)) df[, setdiff(names(df), cols), drop = FALSE] else df
  }

  .build_sheet_list <- function(sub_dt, sub_df) {
    if (has_file_col && has_sheet_col) {
      keys   <- unique(sub_dt[, c(file_col, sheet_col), with = FALSE])
      sheets <- lapply(seq_len(nrow(keys)), function(i) {
        fn <- keys[[file_col]][i]; sn <- keys[[sheet_col]][i]
        rows <- which(sub_dt[[file_col]] == fn & sub_dt[[sheet_col]] == sn)
        list(label = .safe_sheet(paste(fn, sn, sep = "_")),
             data  = .drop(sub_df[rows, , drop = FALSE]))
      })
    } else if (has_file_col) {
      sheets <- lapply(unique(sub_dt[[file_col]]), function(fn) {
        rows <- which(sub_dt[[file_col]] == fn)
        list(label = .safe_sheet(fn), data = .drop(sub_df[rows, , drop = FALSE]))
      })
    } else {
      sheets <- lapply(unique(sub_dt[[sheet_col]]), function(sn) {
        rows <- which(sub_dt[[sheet_col]] == sn)
        list(label = .safe_sheet(sn), data = .drop(sub_df[rows, , drop = FALSE]))
      })
    }
    nms <- vapply(sheets, `[[`, character(1L), "label")
    out <- stats::setNames(lapply(sheets, `[[`, "data"), nms)
    if (verbose)
      for (nm in nms) message(sprintf("  Sheet '%s': %d rows", nm, nrow(out[[nm]])))
    out
  }

  .plain_sheet_list <- function(df) {
    lbl <- .safe_sheet(sheet_name)
    if (verbose) message(sprintf("  Sheet '%s': %d rows", lbl, nrow(df)))
    stats::setNames(list(df), lbl)
  }

  ## (1) Single workbook
  if (to_single_file) {
    sheet_list <- if (has_file_col || has_sheet_col)
      .build_sheet_list(data_dt, data_df)
    else
      .plain_sheet_list(data_df)
    .save(sheet_list, path)
    return(invisible(stats::setNames(path, path)))
  }

  ## (2) Directory: one file per file_col value
  if (!has_file_col)
    stop(sprintf(
      paste0("`path` (\"%s\") is a directory, but `data` has no `%s` column ",
             "to split files by.\n",
             "  Pass a file path ending in .xlsx to write a single workbook instead."),
      path, file_col), call. = FALSE)

  if (!dir.exists(path)) dir.create(path, recursive = TRUE)

  file_vals <- unique(data_dt[[file_col]])
  out_paths <- character(length(file_vals))

  for (i in seq_along(file_vals)) {
    fv     <- file_vals[[i]]
    rows   <- which(data_dt[[file_col]] == fv)
    sub_dt <- data_dt[rows]
    sub_df <- data_df[rows, , drop = FALSE]

    sheet_list <- if (has_sheet_col)
      .build_sheet_list(sub_dt, sub_df)
    else {
      lbl <- .safe_sheet(fv)
      if (verbose) message(sprintf("  Sheet '%s': %d rows", lbl, nrow(sub_df)))
      stats::setNames(list(.drop(sub_df)), lbl)
    }

    out_paths[[i]] <- file.path(path, paste0(fv, ".xlsx"))
    .save(sheet_list, out_paths[[i]])
  }

  invisible(stats::setNames(out_paths, file_vals))
}
