# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Export Nested Data Structures with Hierarchical Directory Organization
#'
#' @description
#' Exports list-columns containing \code{data.frame} or \code{data.table} objects from a
#' \code{data.frame}/\code{data.table} to \code{txt} or \code{csv} files, automatically
#' constructing a hierarchical directory structure from non-nested columns.
#' Exportable nested columns (those holding \code{data.frame}/\code{data.table} elements)
#' are distinguished from non-exportable custom-object columns (e.g. \code{rsplit} from
#' the rsample package); only the former are written to disk by default.
#'
#' @param nest_dt     A \code{data.frame} or \code{data.table} containing at least one
#'   nested list-column. Must have one or more rows.
#' @param group_cols  Optional character vector of column names used to build the
#'   hierarchical output directory structure. When \code{NULL} (default), all non-nested
#'   columns are used automatically.
#' @param nest_cols   Optional character vector of nested column names to export. When
#'   \code{NULL} (default), all columns whose elements are \code{data.frame}/\code{data.table}
#'   objects are exported automatically; custom-object list-columns are reported and skipped.
#'   Specifying a non-\code{data.frame} column triggers a warning and that column is skipped.
#' @param export_path Single character string specifying the root export directory.
#'   Defaults to \code{tempdir()}. Created recursively if it does not exist.
#' @param file_type   Either \code{"txt"} (tab-separated, default) or \code{"csv"}
#'   (comma-separated). Case-insensitive.
#'
#' @return An invisible \code{integer} giving the total number of files successfully written.
#'   Returns \code{0L} when no exportable columns are found or all nested data are empty/\code{NULL}.
#'
#' @details
#' **Nested column classification (mutually exclusive):**
#' \itemize{
#'   \item \emph{Exportable} — every element inherits from \code{data.frame} or \code{data.table}.
#'   \item \emph{Non-exportable} — empty lists or elements of any other class
#'     (e.g. \code{rsplit}, \code{vfold_split}). Reported to the console; never written.
#' }
#'
#' **Directory layout:**
#' \code{export_path / <group1_value> / <group2_value> / <nest_col_name>.<file_type>}
#'
#' **Performance notes:**
#' \itemize{
#'   \item Row data is accessed via \code{.subset2()} (zero-copy column access) rather than
#'     \code{nest_dt[i]}, eliminating per-row \code{data.table} allocation in the hot loop.
#'   \item All \code{n} output directory paths are pre-computed in a single vectorised
#'     \code{do.call(file.path, ...)} call before the loop; only the \code{k} unique paths
#'     are then passed to \code{dir.create()}, replacing \code{n} syscalls with \code{k}
#'     (\code{k <= n}; often \code{k << n} when many rows share the same group).
#'   \item The field separator and output filenames are computed once before the loop.
#'   \item \code{seq_len()} is used instead of \code{1:n} to avoid the \code{1:0} edge-case bug.
#'   \item All list-column introspection uses \code{vapply} with explicit \code{FUN.VALUE} to
#'     guarantee return types and prevent silent coercion.
#' }
#'
#' @section Dependencies:
#' Requires the \pkg{data.table} package for data manipulation and file I/O (\code{fwrite}).
#'
#' @seealso \code{\link[data.table]{fwrite}}
#'
#' @importFrom data.table is.data.table as.data.table fwrite
#' @export
#' @examples
#' # Example 1: Basic nested data export workflow
#' # Step 1: Create nested data structure
#' dt_nest <- w2l_nest(
#'   data = iris,              # Input iris dataset
#'   cols2l = 1:2,             # Columns to be nested
#'   by = "Species"            # Grouping variable
#' )
#'
#' # Step 2: Export nested data to files
#' export_nest(
#'   nest_dt = dt_nest,        # Input nested data.table
#'   nest_cols = "data",       # Column containing nested data
#'   group_cols = c("name", "Species")  # Columns to create directory structure
#' )
#' # Returns the number of files created
#' # Creates directory structure: tempdir()/name/Species/data.txt
#'
#' # Check exported files
#' list.files(
#'   path = tempdir(),         # Default export directory
#'   pattern = "txt",          # File type pattern to search
#'   recursive = TRUE          # Search in subdirectories
#' )
#' # Returns list of created files and their paths
#'
#' # Clean up exported files
#' files <- list.files(
#'   path = tempdir(),         # Default export directory
#'   pattern = "txt",          # File type pattern to search
#'   recursive = TRUE,         # Search in subdirectories
#'   full.names = TRUE         # Return full file paths
#' )
#' file.remove(files)          # Remove all exported files
export_nest <- function(nest_dt,
                        group_cols  = NULL,
                        nest_cols   = NULL,
                        export_path = tempdir(),
                        file_type   = "txt") {

  # ── 0. Dependency check ───────────────────────────────────────────────────────
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required. Install it with install.packages('data.table').")
  }

  # ── 1. Coerce input to data.table ─────────────────────────────────────────────
  # Convert once up-front; all subsequent operations assume data.table semantics.
  if (!data.table::is.data.table(nest_dt)) {
    nest_dt <- data.table::as.data.table(nest_dt)
  }

  # ── 2. Early parameter validation (fail-fast) ─────────────────────────────────
  if (nrow(nest_dt) == 0L) {
    stop("'nest_dt' must not be empty (nrow == 0).")
  }

  if (!is.character(export_path) || length(export_path) != 1L || is.na(export_path)) {
    stop("'export_path' must be a single non-NA character string.")
  }

  # Normalise file_type and resolve separator once — avoids recomputation in the hot loop.
  file_type <- tolower(trimws(file_type))
  if (!file_type %in% c("txt", "csv")) {
    stop("'file_type' must be either \"txt\" or \"csv\".")
  }
  sep <- if (file_type == "txt") "\t" else ","

  # ── 3. Nested column detection (mutually exclusive classification) ─────────────
  # Helper: returns TRUE only when every element of a list-column inherits from
  # data.frame or data.table.  Uses vapply (strict return type) to guard against
  # silent coercion and the all(logical(0)) == TRUE pitfall on empty lists.
  .is_df_list_col <- function(x) {
    if (!is.list(x) || length(x) == 0L) return(FALSE)
    all(vapply(x,
               function(elem) inherits(elem, c("data.frame", "data.table")),
               FUN.VALUE = logical(1L)))
  }

  # Step 1: Identify ALL list-columns (empty lists, custom objects, df/dt columns).
  all_list_cols <- names(nest_dt)[vapply(nest_dt, is.list, FUN.VALUE = logical(1L))]

  if (length(all_list_cols) == 0L) {
    stop("'nest_dt' contains no list-columns (nested columns).")
  }

  # Step 2: Among all list-columns, find those holding data.frame/data.table elements.
  df_nested_cols <- all_list_cols[vapply(nest_dt[, all_list_cols, with = FALSE],
                                         .is_df_list_col,
                                         FUN.VALUE = logical(1L))]

  # Step 3: Remaining list-columns are strictly non-exportable (setdiff guarantees
  # mutual exclusivity — no overlap with df_nested_cols).
  other_list_cols <- setdiff(all_list_cols, df_nested_cols)

  # ── 4. Resolve which nested columns to export ─────────────────────────────────
  if (is.null(nest_cols)) {
    # Auto mode: export only data.frame/data.table nested columns.
    if (length(df_nested_cols) == 0L) {
      stop("No data.frame/data.table nested columns found. ",
           "Specify 'nest_cols' explicitly or convert list-column elements first.")
    }
    nest_cols <- df_nested_cols
    message("[ export_nest ] Auto-selected data.frame/data.table nested columns: ",
            paste(nest_cols, collapse = ", "))
    if (length(other_list_cols) > 0L) {
      message("[ export_nest ] The following columns contain custom objects and will be skipped ",
              "(cannot be written as txt/csv): ",
              paste(other_list_cols, collapse = ", "))
    }
  } else {
    # Manual mode: validate user-supplied column names.
    if (!is.character(nest_cols) || length(nest_cols) == 0L) {
      stop("'nest_cols' must be a non-empty character vector.")
    }
    # Ensure all specified columns actually exist.
    invalid_cols <- setdiff(nest_cols, names(nest_dt))
    if (length(invalid_cols) > 0L) {
      stop("The following columns specified in 'nest_cols' do not exist in 'nest_dt': ",
           paste(invalid_cols, collapse = ", "))
    }
    # Drop any columns that do not hold data.frame/data.table elements.
    non_df_cols <- setdiff(nest_cols, df_nested_cols)
    if (length(non_df_cols) > 0L) {
      warning("The following columns do not contain data.frame/data.table objects ",
              "and will be skipped: ",
              paste(non_df_cols, collapse = ", "), call. = FALSE)
      nest_cols <- intersect(nest_cols, df_nested_cols)
    }
    if (length(nest_cols) == 0L) {
      stop("No valid data.frame/data.table columns remain after filtering.")
    }
  }

  # ── 5. Resolve grouping columns ───────────────────────────────────────────────
  if (is.null(group_cols)) {
    # Auto mode: every non-list column becomes a grouping variable.
    group_cols <- setdiff(names(nest_dt), all_list_cols)
    if (length(group_cols) > 0L) {
      message("[ export_nest ] Auto-selected grouping columns: ",
              paste(group_cols, collapse = ", "))
    } else {
      message("[ export_nest ] No grouping columns found; all files will be written to the root export path.")
    }
  } else {
    if (!is.character(group_cols) || length(group_cols) == 0L) {
      stop("'group_cols' must be a non-empty character vector (or NULL).")
    }
    missing_cols <- setdiff(group_cols, names(nest_dt))
    if (length(missing_cols) > 0L) {
      warning("The following 'group_cols' columns are absent and will be ignored: ",
              paste(missing_cols, collapse = ", "), call. = FALSE)
      group_cols <- intersect(group_cols, names(nest_dt))
    }
    if (length(group_cols) == 0L) {
      message("[ export_nest ] No valid grouping columns remain; files will be written to the root export path.")
    } else {
      message("[ export_nest ] Using grouping columns: ", paste(group_cols, collapse = ", "))
    }
  }

  # ── 6. Pre-compute output filenames (once, outside the hot loop) ──────────────
  # Pattern: {nested_column_name}.{file_type}, e.g. "data.txt", "results.csv"
  filenames        <- paste0(nest_cols, ".", file_type)
  names(filenames) <- nest_cols   # Named vector enables O(1) lookup by column name.

  # ── 7. Vectorised path pre-computation + batch directory creation ─────────────
  # (Improvement merged from Gemini's version)
  #
  # Instead of building each row's directory path inside the hot loop and calling
  # dir.create() n times, we:
  #   (a) leverage file.path()'s vectorised behaviour via do.call() to generate
  #       ALL n directory paths in a single R call — no per-row overhead.
  #   (b) deduplicate with unique() and create only the distinct directories once,
  #       before the loop starts.  When n >> number of unique groups (a common case),
  #       this replaces n syscalls with k syscalls (k = unique group combinations).
  if (length(group_cols) > 0L) {
    # as.character() is applied column-wise to the group sub-table; lapply returns a
    # list of character vectors that do.call(file.path, ...) consumes as positional
    # arguments — fully vectorised, zero row-slice copies.
    group_paths <- do.call(
      file.path,
      c(list(export_path),
        lapply(nest_dt[, group_cols, with = FALSE], as.character))
    )
  } else {
    group_paths <- rep(export_path, nrow(nest_dt))
  }

  # Batch-create every unique subdirectory before entering the write loop.
  # dir.create() is a syscall; eliminating redundant calls matters at scale.
  lapply(unique(group_paths), dir.create, showWarnings = FALSE, recursive = TRUE)

  # ── 8. Main export loop ───────────────────────────────────────────────────────
  # Design rationale:
  #   - seq_len(n) instead of 1:n — avoids the classic 1:0 == c(1, 0) edge case.
  #   - .subset2(nest_dt, col)[[i]] instead of nest_dt[i][[col]] — the latter copies
  #     the entire row into a new data.table on every iteration; .subset2 accesses
  #     the column vector directly (zero additional allocation).
  #   - dir_path is now looked up from the pre-computed group_paths vector (O(1))
  #     rather than being rebuilt per row.
  n_rows      <- nrow(nest_dt)
  total_count <- 0L

  for (i in seq_len(n_rows)) {

    # Retrieve the pre-computed directory path for this row — no string work at all.
    dir_path <- group_paths[i]

    # ---- Write each nested column for this row ----
    for (j in seq_along(nest_cols)) {
      col_name <- nest_cols[j]

      tryCatch({
        # Zero-copy element access: retrieve the list element directly from the
        # column vector without materialising a row-slice data.table.
        nested_elem <- .subset2(nest_dt, col_name)[[i]]

        # Skip NULL values and zero-row data frames silently.
        if (is.null(nested_elem)) next
        if (is.data.frame(nested_elem) && nrow(nested_elem) == 0L) next

        # Coerce to data.table. If already a data.table, as.data.table() passes by
        # reference (no copy); otherwise a single conversion occurs here.
        nested_dt <- data.table::as.data.table(nested_elem)

        # Write to disk using fwrite — the fastest tabular I/O in the data.table ecosystem.
        file_path <- file.path(dir_path, filenames[col_name])
        data.table::fwrite(nested_dt, file = file_path, sep = sep)

        total_count <- total_count + 1L

      }, error = function(e) {
        warning(sprintf("[ export_nest ] Failed to export column '%s' at row %d: %s",
                        col_name, i, conditionMessage(e)),
                call. = FALSE)
      })
    }
  }

  # ── 9. Summary message ────────────────────────────────────────────────────────
  message(sprintf("[ export_nest ] Export complete. %d file(s) written to: %s",
                  total_count, export_path))

  invisible(total_count)
}
