# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Export Data to XLSX Files
#'
#' @description
#' The natural complement to \code{import_xlsx()}.  Takes a combined data
#' object (the kind produced by \code{import_xlsx()} with \code{rbind = TRUE})
#' and writes it back to disk.  The output \strong{destination} is decided by a
#' single \code{path} argument, and \strong{worksheet splitting follows the
#' data automatically} — there are no separate "modes" to choose:
#'
#' \itemize{
#'   \item \strong{\code{path} is a directory} (no \code{.xlsx} extension) —
#'         write \emph{one file per \code{file_col} value} into that directory,
#'         with one worksheet per \code{sheet_col} value inside each file.
#'         This is the transparent round-trip of \code{import_xlsx()}.
#'   \item \strong{\code{path} is a file} (ends in \code{.xlsx}) — write
#'         \emph{everything into a single workbook}.  Worksheets are named
#'         \code{"<file_col>_<sheet_col>"} (or just \code{"<sheet_col>"} /
#'         \code{"<file_col>"} when only one tracking column is present), and
#'         plain data without tracking columns becomes a single sheet.
#' }
#'
#' Columns injected by \code{import_xlsx()} (\code{file_col}, \code{sheet_col})
#' are stripped from the output by default so the exported sheets are identical
#' to the originals.  Plain \code{data.frame}s without any tracking columns
#' (e.g. \code{mtcars}) are supported and are written as a single sheet — but
#' only to a file \code{path}, since there is nothing to split files by.
#'
#' @param data       A \code{data.frame}, \code{data.table}, or \code{tibble}
#'                   to export.  Tracking columns (\code{file_col} /
#'                   \code{sheet_col}) are optional.
#' @param path       \code{character(1)}.  The output destination.  If it ends
#'                   in \code{.xlsx} (case-insensitive) it is treated as a
#'                   \strong{single workbook}; otherwise it is treated as an
#'                   \strong{output directory} and one file is written per
#'                   \code{file_col} value.  Parent directories are created
#'                   recursively as needed.
#' @param file_col   \code{character(1)}.  Name of the column identifying the
#'                   source file.  Default \code{"excel_name"}.
#' @param sheet_col  \code{character(1)}.  Name of the column identifying the
#'                   source sheet.  Default \code{"sheet_name"}.
#' @param sheet_name \code{character(1)}.  Worksheet tab name used when
#'                   \code{data} has neither tracking column (single-sheet
#'                   fallback).  Default \code{"Sheet1"}.
#' @param drop_cols  \code{logical(1)}.  When \code{TRUE} (default) the tracking
#'                   columns are removed from every exported sheet so the
#'                   round-trip is transparent.
#' @param overwrite  \code{logical(1)}.  Allow overwriting existing files.
#'                   Default \code{TRUE}.
#' @param verbose    \code{logical(1)}.  Print a message for every sheet/file
#'                   written.  Default \code{FALSE}.
#'
#' @details
#' \subsection{Why \pkg{writexl}?}{
#'   \pkg{writexl} writes \code{.xlsx} via a minimal C library with no Java or
#'   Perl dependency.  It is faster than \pkg{openxlsx} for plain export and
#'   produces smaller files, at the cost of no cell formatting, formulas, or
#'   styles.  For those, use \pkg{openxlsx} / \pkg{openxlsx2}.
#' }
#' \subsection{Sheet-name sanitisation}{
#'   Excel sheet names are limited to 31 characters and may not contain
#'   \code{[ ] * ? / \\ :}.  Both constraints are enforced automatically.
#' }
#' \subsection{Directory vs. file dispatch}{
#'   The single \code{path} argument is classified purely by its extension: a
#'   trailing \code{.xlsx} means "one workbook", anything else means "a
#'   directory of files".  If you want a directory whose name happens to end in
#'   \code{.xlsx}, append a trailing slash, or pass an explicit file name.
#' }
#'
#' @return Invisibly, a named \code{character} vector of written file paths:
#'   named by \code{file_col} value in directory mode, or by \code{path} in
#'   single-workbook mode.
#'
#' @importFrom data.table is.data.table as.data.table copy
#' @importFrom writexl write_xlsx
#' @export
#' @examples
#' # Example: Excel file export demonstrations
#' # Example 1: Export a plain data.frame to a single workbook
#' out_file <- file.path(tempdir(), "test.xlsx")
#' export_xlsx(
#'   mtcars,                             # Data to export (no tracking columns)
#'   path       = out_file,              # Ends in .xlsx -> one workbook
#'   sheet_name = "test"                 # Worksheet tab name for the single sheet
#' )
#' # Clean up the generated file
#' file.remove(out_file)
#'
#' # Example 2: Split into one file per group
#' out_files <- export_xlsx(
#'   iris,                               # Data to export
#'   path      = tempdir(),              # A directory -> one file per file_col value
#'   file_col  = "Species",              # Column whose values name the output files
#'   drop_cols = FALSE                   # Keep the Species column in each output file
#' )
#' # Clean up the generated files (export_xlsx returns the written paths)
#' file.remove(out_files)
export_xlsx <- function(data,
                        path,
                        file_col   = "excel_name",
                        sheet_col  = "sheet_name",
                        sheet_name = "Sheet1",
                        drop_cols  = TRUE,
                        overwrite  = TRUE,
                        verbose    = FALSE) {
  
  # ── 1. Input validation ────────────────────────────────────────────────────
  
  if (!is.data.frame(data))
    stop("`data` must be a data.frame, data.table, or tibble.", call. = FALSE)
  
  if (!is.character(path) || length(path) != 1L || is.na(path) || !nzchar(path))
    stop("`path` must be a single non-empty character string.", call. = FALSE)
  
  if (!is.character(sheet_name) || length(sheet_name) != 1L ||
      is.na(sheet_name) || !nzchar(sheet_name))
    stop("`sheet_name` must be a single non-empty character string.", call. = FALSE)
  
  if (!is.logical(overwrite) || length(overwrite) != 1L || is.na(overwrite))
    stop("`overwrite` must be a single non-NA logical.", call. = FALSE)
  
  # Keep a plain data.frame for writexl (preserves row.names); use data.table
  # only for fast grouping / row indexing.
  data_df <- as.data.frame(data)
  data_dt <- if (data.table::is.data.table(data))
    data.table::copy(data)
  else
    data.table::as.data.table(data)
  
  has_file_col  <- file_col  %in% names(data_df)
  has_sheet_col <- sheet_col %in% names(data_df)
  
  # Classify the destination: file (single workbook) vs directory (split).
  to_single_file <- grepl("\\.xlsx$", path, ignore.case = TRUE)
  
  # ── 2. Helpers ─────────────────────────────────────────────────────────────
  
  .safe_sheet <- function(x) {
    x <- gsub("[\\[\\]\\*\\?\\/\\\\:]", "_", x, perl = TRUE)
    substr(x, 1L, 31L)
  }
  
  .drop <- function(df) {
    if (!drop_cols) return(df)
    cols <- intersect(c(if (has_file_col) file_col, if (has_sheet_col) sheet_col),
                      names(df))
    if (length(cols)) df[, setdiff(names(df), cols), drop = FALSE] else df
  }
  
  # Build a named list of data.frames keyed by whichever tracking columns exist.
  # Row positions come from data_dt (fast); slices come from data_df (safe).
  .build_sheet_list <- function(sub_dt, sub_df) {
    if (has_file_col && has_sheet_col) {
      keys   <- unique(sub_dt[, c(file_col, sheet_col), with = FALSE])
      sheets <- lapply(seq_len(nrow(keys)), function(i) {
        fn <- keys[[file_col]][i]; sn <- keys[[sheet_col]][i]
        rows <- which(sub_dt[[file_col]] == fn & sub_dt[[sheet_col]] == sn)
        list(label = .safe_sheet(paste(fn, sn, sep = "_")),
             data  = .drop(sub_df[rows, , drop = FALSE]))
      })
    } else if (has_file_col) {
      sheets <- lapply(unique(sub_dt[[file_col]]), function(fn) {
        rows <- which(sub_dt[[file_col]] == fn)
        list(label = .safe_sheet(fn), data = .drop(sub_df[rows, , drop = FALSE]))
      })
    } else {
      sheets <- lapply(unique(sub_dt[[sheet_col]]), function(sn) {
        rows <- which(sub_dt[[sheet_col]] == sn)
        list(label = .safe_sheet(sn), data = .drop(sub_df[rows, , drop = FALSE]))
      })
    }
    
    nms <- vapply(sheets, `[[`, character(1L), "label")
    out <- stats::setNames(lapply(sheets, `[[`, "data"), nms)
    if (verbose)
      for (nm in nms) message(sprintf("  Sheet '%s': %d rows", nm, nrow(out[[nm]])))
    out
  }
  
  .plain_sheet_list <- function(df) {
    lbl <- .safe_sheet(sheet_name)
    if (verbose) message(sprintf("  Sheet '%s': %d rows", lbl, nrow(df)))
    stats::setNames(list(df), lbl)
  }
  
  .save <- function(sheet_list, file) {
    dir_path <- dirname(file)
    if (!dir.exists(dir_path)) dir.create(dir_path, recursive = TRUE)
    if (!overwrite && file.exists(file))
      stop(sprintf("File already exists (overwrite = FALSE): %s", file),
           call. = FALSE)
    writexl::write_xlsx(sheet_list, path = file)
    if (verbose) message(sprintf("Saved: %s", file))
  }
  
  # ── 3. Dispatch — only two destinations ─────────────────────────────────────
  
  ## (1) Single workbook: path ends in .xlsx
  if (to_single_file) {
    sheet_list <- if (has_file_col || has_sheet_col)
      .build_sheet_list(data_dt, data_df)
    else
      .plain_sheet_list(data_df)
    .save(sheet_list, path)
    return(invisible(stats::setNames(path, path)))
  }
  
  ## (2) Directory: one file per file_col value
  if (!has_file_col)
    stop(sprintf(
      paste0("`path` (\"%s\") is a directory, but `data` has no `%s` column ",
             "to split files by.\n  Pass a file path ending in .xlsx to write ",
             "a single workbook instead."),
      path, file_col), call. = FALSE)
  
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)
  
  file_vals <- unique(data_dt[[file_col]])
  out_paths <- character(length(file_vals))
  
  for (i in seq_along(file_vals)) {
    fv     <- file_vals[[i]]
    rows   <- which(data_dt[[file_col]] == fv)
    sub_dt <- data_dt[rows]
    sub_df <- data_df[rows, , drop = FALSE]
    
    sheet_list <- if (has_sheet_col)
      .build_sheet_list(sub_dt, sub_df)
    else {
      lbl <- .safe_sheet(fv)
      if (verbose)
        message(sprintf("  Sheet '%s': %d rows", lbl, nrow(sub_df)))
      stats::setNames(list(.drop(sub_df)), lbl)
    }
    
    out_paths[[i]] <- file.path(path, paste0(fv, ".xlsx"))
    .save(sheet_list, out_paths[[i]])
  }
  
  invisible(stats::setNames(out_paths, file_vals))
}
