# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Format Numeric Columns to Fixed-Decimal Character Strings
#'
#' @param data        A data.frame or data.table. The input dataset.
#' @param cols        A character or integer vector specifying columns to format.
#'                    If NULL (default), all numeric columns are formatted.
#' @param digits      A non-negative integer specifying decimal places. Defaults to 2.
#' @param percentage  Logical. If TRUE, values are multiplied by 100 and a "%"
#'                    sign is appended. Defaults to FALSE.
#' @param nan_as_na   Logical. If TRUE, NaN is treated identically to NA and
#'                    coerced to NA_character_. If FALSE (default), NaN is
#'                    preserved as the string "NaN".
#'
#' @return A data.table with the specified numeric columns formatted as character
#'         strings. The original object is never modified.
#'
#' @details
#' The function processes columns in the following order:
#' \enumerate{
#'   \item Validates all input parameters with informative error messages.
#'   \item Copies the input only once: data.table inputs are deep-copied via
#'         \code{copy()}; data.frame inputs are copied implicitly by
#'         \code{as.data.table()}, avoiding a redundant second copy.
#'   \item Resolves \code{cols} to a character vector of valid numeric column
#'         names, warning and skipping any non-numeric columns specified.
#'   \item Applies a vectorised formatting function via
#'         \code{lapply(.SD, fn)} and \code{:=}, so all target columns are
#'         dispatched in a single data.table call rather than a column-by-column
#'         loop.
#' }
#'
#' NA and NaN handling:
#' \itemize{
#'   \item \code{NA_real_} is always returned as \code{NA_character_}.
#'   \item \code{NaN} is returned as \code{"NaN"} by default. Set
#'         \code{nan_as_na = TRUE} to coerce it to \code{NA_character_} instead.
#' }
#'
#' Rounding uses explicit \code{round()} before \code{sprintf()} to guarantee
#' consistent results across platforms (Windows, Linux, macOS), where the
#' underlying C library's rounding behaviour may otherwise differ.
#'
#' @note
#' \itemize{
#'   \item \code{data} must be a data.frame or data.table.
#'   \item Integer column indices in \code{cols} are converted to column names
#'         internally; duplicates are silently removed.
#'   \item \code{digits} accepts numeric values such as \code{2.0} and coerces
#'         them to integer; non-integer-valued numbers raise an error.
#'   \item The function depends only on \code{data.table} and base R.
#' }
#'
#' @import data.table
#' @export
#' @examples
#' # Example: Number formatting demonstrations
#'
#' # Setup test data
#' dt <- data.table::data.table(
#'   a = c(0.1234, 0.5678),      # Numeric column 1
#'   b = c(0.2345, 0.6789),      # Numeric column 2
#'   c = c("text1", "text2")     # Text column
#' )
#'
#' # Example 1: Format all numeric columns
#' format_digits(
#'   dt,                         # Input data table
#'   digits = 2                  # Round to 2 decimal places
#' )
#'
#' # Example 2: Format specific column as percentage
#' format_digits(
#'   dt,                         # Input data table
#'   cols = c("a"),              # Only format column 'a'
#'   digits = 2,                 # Round to 2 decimal places
#'   percentage = TRUE           # Convert to percentage
#' )
format_digits <- function(data,
                          cols       = NULL,
                          digits     = 2L,
                          percentage = FALSE,
                          nan_as_na  = FALSE) {

  # -- 1. Input validation ---------------------------------------------------
  if (!is.data.frame(data)) {
    stop("'data' must be a data.frame or data.table.", call. = FALSE)
  }
  if (!is.logical(percentage) || length(percentage) != 1L || is.na(percentage)) {
    stop("'percentage' must be a single non-NA logical value (TRUE or FALSE).",
         call. = FALSE)
  }
  if (!is.logical(nan_as_na) || length(nan_as_na) != 1L || is.na(nan_as_na)) {
    stop("'nan_as_na' must be a single non-NA logical value (TRUE or FALSE).",
         call. = FALSE)
  }

  # -- 2. Coerce digits to integer (tolerates inputs like 2.0) --------------
  digits <- suppressWarnings(as.integer(digits))
  if (is.na(digits) || length(digits) != 1L || digits < 0L) {
    stop("'digits' must be a single non-negative integer (e.g. 0, 1, 2, ...).",
         call. = FALSE)
  }

  # -- 3. Single-copy strategy -----------------------------------------------
  # data.table input  -> copy() performs one explicit deep copy.
  # data.frame input  -> as.data.table() allocates a new object; no second
  #                      copy() needed, avoiding the double-allocation present
  #                      in the original implementation.
  result <- if (is.data.table(data)) copy(data) else as.data.table(data)

  # -- 4. Resolve cols to a valid character vector of column names -----------
  if (is.null(cols)) {
    # vapply with a fixed return type is safer and faster than sapply
    target_cols <- names(result)[vapply(result, is.numeric, logical(1L))]

  } else {
    if (!is.numeric(cols) && !is.character(cols)) {
      stop("'cols' must be a character vector of column names or an integer ",
           "vector of column indices.", call. = FALSE)
    }
    if (length(cols) == 0L) {
      stop("'cols' must not be empty. Pass NULL to format all numeric columns.",
           call. = FALSE)
    }

    # Convert integer indices to column names
    if (is.numeric(cols)) {
      cols    <- as.integer(cols)
      bad_idx <- cols < 1L | cols > ncol(result)
      if (any(bad_idx)) {
        stop("Column indices out of range (valid range: 1-", ncol(result), "): ",
             paste(cols[bad_idx], collapse = ", "), call. = FALSE)
      }
      cols <- names(result)[cols]
    }

    # Drop duplicates to prevent undefined behaviour from repeated := assignment
    cols <- unique(cols)

    # Verify all names exist
    missing_cols <- setdiff(cols, names(result))
    if (length(missing_cols) > 0L) {
      stop("The following columns were not found in 'data': ",
           paste(missing_cols, collapse = ", "), call. = FALSE)
    }

    # Use .subset2 to extract each column vector directly, bypassing the
    # [.data.table dispatch overhead - measurably faster on wide tables.
    is_num <- vapply(cols,
                     function(cn) is.numeric(.subset2(result, cn)),
                     logical(1L))
    non_numeric <- cols[!is_num]
    if (length(non_numeric) > 0L) {
      warning("The following columns are not numeric and will be skipped: ",
              paste(non_numeric, collapse = ", "), call. = FALSE)
      cols <- cols[is_num]
    }
    if (length(cols) == 0L) {
      message("No formattable numeric columns remain. Returning a copy of the input.")
      return(result)
    }
    target_cols <- cols
  }

  # -- 5. Edge case: no numeric columns present ------------------------------
  if (length(target_cols) == 0L) {
    message("'data' contains no numeric columns. Returning a copy of the input.")
    return(result)
  }

  # -- 6. Build the format template once; reuse across all target columns ----
  fmt_tpl <- paste0("%.", digits, "f", if (percentage) "%%" else "")

  # -- 7. Vectorised formatting function -------------------------------------
  # Design rationale:
  #   a) Explicit round() before sprintf() ensures identical rounding across
  #      platforms; sprintf alone delegates to the C library, whose tie-breaking
  #      behaviour differs between Windows, Linux, and macOS.
  #   b) NA_real_ and NaN are handled separately:
  #        - NA_real_ -> always NA_character_
  #        - NaN      -> "NaN" by default; NA_character_ when nan_as_na = TRUE
  #   c) data.table::fifelse (C-level) is used instead of base ifelse to avoid
  #      R-level type checking and recycling logic (~3-5x faster on large vectors).
  fmt_fn <- if (percentage) {
    function(x) {
      val <- sprintf(fmt_tpl, round(x * 100, digits))
      val <- fifelse(is.na(x) & !is.nan(x), NA_character_, val)
      if (nan_as_na) val <- fifelse(is.nan(x), NA_character_, val)
      val
    }
  } else {
    function(x) {
      val <- sprintf(fmt_tpl, round(x, digits))
      val <- fifelse(is.na(x) & !is.nan(x), NA_character_, val)
      if (nan_as_na) val <- fifelse(is.nan(x), NA_character_, val)
      val
    }
  }

  # -- 8. Batch in-place update via data.table's := -------------------------
  # lapply(.SD, fmt_fn) dispatches all target columns in a single data.table
  # call, reducing R->C layer transitions compared to a for + set() loop.
  result[, (target_cols) := lapply(.SD, fmt_fn), .SDcols = target_cols][]

  return(result)
}
