# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Extract Path Segments or Filenames from File Paths
#'
#' @description
#' `get_path_info` is a merged, upgraded replacement for `get_path_segment` and
#' `get_filename`. It operates in two modes:
#'   - **Mode A (when `n` is specified)**: Extract a specific path segment by
#'     position, supporting forward indexing, reverse indexing, and range extraction.
#'   - **Mode B (when `n = NULL`)**: Extract the filename, with optional removal
#'     of the file extension and/or the directory prefix.
#'
#' @param paths A `character` vector of file system paths.
#'   Supports mixed separators (`/` and `\\`) and Windows drive letters (e.g. `C:`).
#'
#' @param n A `numeric` segment index. Defaults to `NULL` (enters filename mode).
#'   - Positive integer: forward index from the path start; `1` = first segment.
#'   - Negative integer: reverse index from the path end; `-1` = last segment
#'     (i.e. the filename segment).
#'   - Length-2 vector: extract a contiguous range, e.g. `c(2, 4)` or `c(-3, -1)`.
#'   - `0` is not allowed.
#'
#' @param rm_extension A `logical(1)` flag controlling extension removal.
#'   Defaults to `TRUE`.
#'   - In Mode B (`n = NULL`): always applied.
#'   - In Mode A: **only applied when `n == -1`** (explicitly targeting the filename
#'     segment). Has no effect for intermediate directory segments (e.g. `n = 2`).
#'
#' @param rm_path A `logical(1)` flag controlling whether the directory prefix is
#'   stripped, keeping only the filename. Defaults to `TRUE`.
#'   Only applies in Mode B (`n = NULL`); ignored when `n` is specified.
#'
#' @return A `character` vector of the same length as `paths`:
#'   - Returns the extracted segment string when the segment exists.
#'   - Returns `NA_character_` when the segment index exceeds the path depth,
#'     the input element is `NA`, or the path reduces to empty after normalisation
#'     (e.g. `"C:/"`, `"/"`).
#'
#' @details
#' **Path normalisation (internal, fully vectorised):**
#' 1. All backslashes and consecutive slashes are collapsed to a single `/`.
#' 2. Windows drive letter prefixes (`C:`, `D:`, etc.) are stripped.
#' 3. Leading and trailing `/` characters are removed.
#' 4. Paths that are empty after the above steps (e.g. original inputs `"C:/"`,
#'    `"/"`, `""`) are coerced to `NA_character_`.
#'
#' **Extension-stripping behaviour (internal `.strip_ext` helper):**
#' | Input             | Output          | Notes                                      |
#' |-------------------|-----------------|--------------------------------------------|
#' | `"report.txt"`    | `"report"`      | Standard file — last extension removed     |
#' | `"data.tar.gz"`   | `"data.tar"`    | Compound extension — only last level removed|
#' | `".bashrc"`       | `".bashrc"`     | Pure dot-file (no second dot) — unchanged  |
#' | `".report.xlsx"`  | `".report"`     | Dot-file with extension — extension removed|
#' | `"no_ext"`        | `"no_ext"`      | No extension — returned as-is              |
#' | `"file."`         | `"file."`       | Trailing isolated dot — returned as-is     |
#'
#' **NA safety:**
#' `strsplit(NA_character_, ...)` returns `list(NA)` with `length` 1, not
#' `character(0)`. Consequently, every `vapply` callback guards against NA paths
#' with an explicit `anyNA(x)` check rather than `length(x) == 0`.
#'
#' @seealso [base::basename()], [tools::file_path_sans_ext()]
#' @export
#' @examples
#' paths <- c("C:/Users/foo/Documents/report.xlsx",
#'            "/home/user/.bashrc",
#'            "relative/path/to/data.csv",
#'            ".hidden.tar.gz",
#'            NA_character_)
#'
#' # Mode B: filename only, extension stripped (default)
#' get_path_info(paths)
#'
#' # Mode B: filename only, extension preserved
#' get_path_info(paths, rm_extension = FALSE)
#'
#' # Mode B: full normalised path, extension stripped
#' get_path_info(paths, rm_path = FALSE)
#'
#' # Mode A: extract the 2nd path segment
#' get_path_info(paths, n = 2)
#'
#' # Mode A: extract the last segment with extension stripped (n = -1 linkage)
#' get_path_info(paths, n = -1, rm_extension = TRUE)
#'
#' # Mode A: range extraction
#' get_path_info(paths, n = c(2, 3))
get_path_info <- function(paths,
                          n            = NULL,
                          rm_extension = TRUE,
                          rm_path      = TRUE) {

  # ── 1. Input validation ──────────────────────────────────────────────────────
  if (missing(paths))
    stop("Argument 'paths' is missing", call. = FALSE)
  if (!is.character(paths))
    stop("'paths' must be a character vector", call. = FALSE)
  if (length(paths) == 0L)
    return(character(0L))

  if (!is.null(n)) {
    if (!is.numeric(n))
      stop("'n' must be numeric", call. = FALSE)
    if (length(n) > 2L)
      stop("'n' must be a single integer or a length-2 integer vector", call. = FALSE)
    if (any(n == 0))
      stop("'n' must not contain 0", call. = FALSE)
    n <- as.integer(n)  # Coerce to integer to eliminate floating-point comparison risk
  }

  if (!is.logical(rm_extension) || length(rm_extension) != 1L)
    stop("'rm_extension' must be a single logical value", call. = FALSE)
  if (!is.logical(rm_path) || length(rm_path) != 1L)
    stop("'rm_path' must be a single logical value", call. = FALSE)

  # Both flags FALSE with no 'n': no transformation will occur — warn the caller
  if (is.null(n) && !rm_extension && !rm_path)
    warning(
      "Both 'rm_extension' and 'rm_path' are FALSE and 'n' is not specified; ",
      "returning normalised paths unchanged.",
      call. = FALSE
    )

  # ── 2. Path normalisation (vectorised, order-sensitive) ──────────────────────
  # Step order is critical: the drive letter must be stripped BEFORE leading
  # slashes are removed, otherwise "C:/" would lose its "/" first and leave
  # "C:" which no longer matches the drive-letter pattern.
  norm <- gsub("\\\\+|/+", "/", paths)   # ① Backslashes & repeated slashes → single "/"
  norm <- sub("^[A-Za-z]:", "", norm)     # ② Strip Windows drive letter (C:, D:, …)
  norm <- gsub("^/+|/+$", "", norm)       # ③ Remove leading and trailing slashes
  # Paths that are empty after normalisation ("C:/", "/", "", …) become NA
  norm[!is.na(norm) & norm == ""] <- NA_character_

  # ── 3. Path splitting ────────────────────────────────────────────────────────
  # Important: strsplit(NA_character_) returns list(NA) with length 1, NOT
  # character(0). Downstream code must therefore use anyNA(x), not length(x) == 0,
  # to detect NA paths safely.
  segs <- strsplit(norm, "/", fixed = TRUE)

  # ── 4. Internal helper: strip the last file extension (vectorised) ───────────
  # Logic (two-layer ifelse — explicit and regex-free for the NA/dot-file cases):
  #   Layer 1: NA or empty string → pass through unchanged.
  #   Layer 2: grepl("^\\.[^.]*$") matches "dot-files with no second dot"
  #            (e.g. ".bashrc", ".gitignore") → leave unchanged.
  #            All other inputs → sub("\\.[^.]+$", "") removes the last ".xxx".
  #
  # Note: [^.]+ in the sub pattern requires at least one non-dot character after
  # the dot, so "file." (trailing isolated dot) is not matched and passes through.
  .strip_ext <- function(x) {
    ifelse(
      is.na(x) | x == "",
      x,
      ifelse(
        grepl("^\\.[^.]*$", x, perl = TRUE),  # Pure dot-file (.bashrc class)
        x,
        sub("\\.[^.]+$", "", x)               # Remove last extension (handles compound too)
      )
    )
  }

  # ── 5. Branching logic ───────────────────────────────────────────────────────
  if (!is.null(n)) {
    # ── Mode A: segment extraction ───────────────────────────────────────────────
    if (length(n) == 1L) {
      # Single index: forward (n > 0) or reverse (n < 0)
      result <- vapply(segs, FUN.VALUE = NA_character_, function(x) {
        if (anyNA(x)) return(NA_character_)   # NA path — short-circuit immediately
        len <- length(x)
        pos <- if (n > 0L) n else len + n + 1L
        if (pos >= 1L && pos <= len) x[[pos]] else NA_character_
      })

      # rm_extension linkage: by convention, only applied when n == -1L, which
      # unambiguously targets the filename segment. Stripping an extension from
      # an intermediate directory segment (e.g. n = 2) is semantically meaningless.
      if (n == -1L && rm_extension) {
        result <- .strip_ext(result)
      }

    } else {
      # Range extraction: collapse segments [pos1, pos2] joined by "/"
      result <- vapply(segs, FUN.VALUE = NA_character_, function(x) {
        if (anyNA(x)) return(NA_character_)
        len  <- length(x)
        pos1 <- if (n[1L] > 0L) n[1L] else len + n[1L] + 1L
        pos2 <- if (n[2L] > 0L) n[2L] else len + n[2L] + 1L
        # Auto-sort endpoints so the caller may supply them in any order
        if (pos1 > pos2) { tmp <- pos1; pos1 <- pos2; pos2 <- tmp }
        # Strict boundary check: either endpoint out-of-range → NA
        if (pos1 >= 1L && pos2 <= len) {
          paste(x[pos1:pos2], collapse = "/")
        } else {
          NA_character_
        }
      })
    }

  } else {
    # ── Mode B: filename mode (n = NULL) ─────────────────────────────────────────
    if (rm_path) {
      # Extract only the last path segment (equivalent to basename on normalised paths)
      result <- vapply(segs, FUN.VALUE = NA_character_, function(x) {
        if (anyNA(x)) return(NA_character_)
        x[[length(x)]]
      })
      if (rm_extension) result <- .strip_ext(result)

    } else {
      # Retain the full normalised path, optionally stripping the final segment's extension
      if (rm_extension) {
        result <- vapply(segs, FUN.VALUE = NA_character_, function(x) {
          if (anyNA(x)) return(NA_character_)
          len      <- length(x)
          x[[len]] <- .strip_ext(x[[len]])  # Only the filename segment (last) is modified
          paste(x, collapse = "/")
        })
      } else {
        result <- vapply(segs, FUN.VALUE = NA_character_, function(x) {
          if (anyNA(x)) NA_character_ else paste(x, collapse = "/")
        })
      }
    }
  }

  # vapply already guarantees a character vector; explicit coercion is a final safeguard
  as.character(result)
}
