# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Extract specific parts of the file path
#' 
#' This function extracts the base name of the file(s) from the given path(s), with options to remove the file extension and/or the directory path.
#' 
#' @param paths character vector. A string or a character vector representing the full path(s) to the file(s).
#' @param remove_extension logical, optional. If TRUE, the file extensions are removed from the filenames. Default is TRUE.
#' @param remove_path logical, optional. If TRUE, the directory paths are removed, leaving only the filenames. Default is TRUE.
#'
#' @return character vector. A string or a character vector representing the processed file name(s).
#' 
#' @export
#' 
#' @note
#' Ensure that the `paths` parameter is a character vector. The function will stop with an error if `paths` is not a character vector.
#' @examples
#' xlsx_files <- mintyr_example(mintyr_examples("xlsx_test"))
#' xlsx_files
#' get_filename(xlsx_files)
#' get_filename(xlsx_files, remove_extension = FALSE)
#' get_filename(xlsx_files, remove_path = FALSE)
get_filename <- function(paths, remove_extension = TRUE, remove_path = TRUE) {
  # Check if paths is a character vector
  if (!is.character(paths)) {
    stop("paths must be a character vector.")
  }
  
  # Remove the directory path if remove_path is TRUE
  if (remove_path) {
    paths <- basename(paths)
  }
  
  # Remove the file extension if remove_extension is TRUE
  if (remove_extension) {
    paths <- tools::file_path_sans_ext(paths)
  }
  
  return(paths)
}
