# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Advanced Filename Extraction from File Paths
#'
#' @description
#' A robust `filename` extraction utility providing comprehensive path processing 
#' with granular control over filename transformation.
#'
#' @param paths A `character` vector containing file system paths.
#'   Must be valid and accessible path strings.
#'
#' @param rm_extension A `logical` flag controlling file extension removal:
#'   - `TRUE`: Strips file extensions from filenames
#'   - `FALSE`: Preserves complete filename with extension
#'   Default is `TRUE`.
#'
#' @param rm_path A `logical` flag managing directory path handling:
#'   - `TRUE`: Extracts only the filename, discarding directory information
#'   - `FALSE`: Retains complete path information
#'   Default is `TRUE`.
#'
#' @details
#' Comprehensive Path Processing Features:
#' \itemize{
#'   \item Intelligent input validation
#'   \item Flexible filename transformation
#'   \item Robust handling of diverse path formats
#'   \item Configurable extraction strategies
#'   \item Minimal performance overhead
#' }
#'
#' Processing Workflow:
#' \enumerate{
#'   \item Validates input path vector
#'   \item Handles empty input scenarios
#'   \item Optionally removes directory paths using [`base::basename()`]
#'   \item Optionally strips file extensions via regex substitution
#' }
#'
#' Extension Handling Strategies:
#' \itemize{
#'   \item Supports multi-dot filenames
#'   \item Removes the last file extension
#'   \item Preserves complex filename structures
#'   \item Compatible with various file naming conventions
#' }
#'
#' @return A `character` vector of processed filenames with applied transformations.
#'
#' @note
#' Critical Behavioral Considerations:
#' \itemize{
#'   \item Requires valid `character` input paths
#'   \item Supports processing multiple file paths simultaneously
#'   \item Warns when no transformations are requested
#'   \item Handles edge cases like empty vectors gracefully
#'   \item Preserves original input order
#' }
#'
#' @seealso
#' \itemize{
#'   \item [`base::basename()`] for basic filename extraction
#'   \item [`base::file.path()`] for path manipulation
#'   \item [`tools::file_ext()`] for extension handling
#' }
#'
#' @export
#' @examples
#' xlsx_files <- mintyr_example(mintyr_examples("xlsx_test"))
#' xlsx_files
#' get_filename(xlsx_files) # Keep only file names
#' get_filename(xlsx_files, rm_extension = FALSE) # Keep extension
#' get_filename(xlsx_files, rm_path = FALSE) # Keep path
get_filename <- function(paths, rm_extension = TRUE, rm_path = TRUE) {

  # Input validation
  if (missing(paths)) {
    stop("Parameter 'paths' cannot be empty")
  }

  if (!is.character(paths)) {
    stop("'paths' must be a character vector")
  }

  # Handle empty vector
  if (length(paths) == 0) {
    return(character(0))
  }

  # Warn if both parameters are FALSE
  if (!rm_extension && !rm_path) {
    warning("Setting both rm_extension=FALSE and rm_path=FALSE returns the original paths")
  }

  # Process paths
  result <- if (rm_path) basename(paths) else paths

  # Process extensions
  if (rm_extension) {
    result <- sub("\\.[^.]*$", "", result)
  }

  return(result)
}
