# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Extract Specific Segments from File Paths
#'
#' The `get_path_segment` function extracts specific segments from file paths provided as character strings. Segments can be extracted from either the beginning or the end of the path, depending on the value of `n`.
#'
#' @param paths A non-empty character vector containing file paths, where each path is a string with segments separated by forward slashes (`/`). This parameter cannot be empty.
#' @param n An integer specifying which segment to extract from each path. If `n` is positive, the function extracts the `n`-th segment from the beginning of the path. If `n` is negative, the function extracts the `n`-th segment from the end of the path. `n` cannot be zero.
#'
#' @return A character vector of the extracted segments. If a path does not have the requested segment, `NA_character_` is returned for that path.
#'
#' @details
#' The function operates as follows:
#' \enumerate{
#'   \item Validates that `paths` is a non-empty character vector and that `n` is a non-zero numeric value.
#'   \item Splits each path in `paths` into segments based on the forward slash (`/`) delimiter.
#'   \item Extracts the specified segment from each set of path segments:
#'   \itemize{
#'     \item If `n > 0`, the function extracts the `n`-th segment counting from the start of the path.
#'     \item If `n < 0`, the function extracts the `n`-th segment counting from the end of the path.
#'   }
#'   \item If a path does not contain the specified segment, `NA_character_` is returned for that path.
#' }
#'
#' @note
#' - The `paths` parameter must be a non-empty character vector.
#' - The `n` parameter must be a non-zero numeric value.
#' - If `n` is zero, the function will raise an error.
#' - The function handles empty strings and paths with consecutive slashes appropriately.
#'  
#' @export
#' @examples
#' # Example usage demonstrations
#' paths <- c("/home/user/documents", "/var/log/system", "/usr/local/bin")
#' # Positive index example
#' get_path_segment(paths, 2)
#' # Negative index example
#' get_path_segment(paths, -2)
get_path_segment <- function(paths, n = 1) {
  # Check if paths parameter is provided
  if (missing(paths)) stop("Parameter 'paths' cannot be empty")

  # Validate paths is a character vector
  if (!is.character(paths)) stop("'paths' must be character")

  # Return empty character vector if paths is empty
  if (length(paths) == 0) return(character(0))

  # Validate n is numeric
  if (!is.numeric(n)) stop("'n' must be numeric")

  # Prevent zero index
  if (n == 0) stop("'n' cannot be 0")

  # Split paths into segments
  segments <- strsplit(paths, "/")

  # Extract specific path segments
  result <- sapply(segments, function(x) {
    if (n > 0) {
      # Positive index: count from the beginning
      # Return segment if index exists, otherwise return NA
      if (length(x) >= n) x[n] else NA_character_
    } else {
      # Negative index: count from the end
      # Convert negative index to positive position
      pos <- length(x) + n + 1

      # Return segment if position is valid, otherwise return NA
      if (pos > 0 && pos <= length(x)) x[pos] else NA_character_
    }
  })

  return(result)
}
