# WARNING - Generated by {fusen} from dev/flat_import_export.Rmd: do not edit by hand # nolint: line_length_linter.

#' Import Data from XLSX Files
#'
#' @description
#' A high-performance function for importing data from one or multiple Excel
#' files into \code{data.table} format, with fine-grained control over source
#' tracking columns, sheet selection, row skipping, multi-row headers, and
#' optional parallel reading across (file, sheet) pairs.
#'
#' Performance characteristics:
#' \itemize{
#'   \item \code{excel_sheets()} called exactly once per file (cached).
#'   \item The real cost of an Excel import is \code{read_excel()} parsing,
#'         which is single-threaded C++ and \emph{not} affected by the
#'         \code{data.table} thread pool. The flat (file x sheet) task list is
#'         therefore read in parallel \strong{across processes} when
#'         \code{workers > 1}: a fork pool on Unix/macOS, a PSOCK cluster on
#'         Windows. The cluster / fork pool is always torn down on exit.
#'   \item \code{setDT()} converts tibbles in-place — zero vector copies.
#'   \item Tracking columns injected via \code{:=} on small per-sheet tables
#'         \emph{before} the single final \code{rbindlist}.
#'   \item The final \code{rbindlist} uses the ambient \code{data.table} thread
#'         pool; tune it globally with \code{\link[data.table]{setDTthreads}} if
#'         needed. Workers are pinned to a single thread during the read phase
#'         so parallel processes do not oversubscribe cores.
#' }
#'
#' @param file       Non-empty \code{character} vector of paths to existing
#'                   \code{.xlsx} / \code{.xls} files.
#' @param combine    \code{logical(1)}. \code{TRUE} (default) binds all sheets
#'                   into a single \code{data.table}. \code{FALSE} returns a
#'                   flat named list keyed as \code{"<filename>_<sheetname>"}.
#' @param sheet      Positive \code{integer} vector, \code{character} vector of
#'                   sheet names, or \code{NULL} (default, every sheet).
#'                   Indices / names must exist in all supplied files.
#' @param skip       Non-negative \code{integer(1)}. Number of rows to skip
#'                   before the header (e.g. a title row). Default \code{0L}.
#' @param header_rows Positive \code{integer(1)}. Number of header rows below
#'                   the skipped rows. Default \code{1L} (ordinary sheets).
#'                   Values \code{> 1} combine the rows into one name per
#'                   column (see Details); data start on the next row.
#' @param header_sep \code{character(1)}. Separator used to join the levels of
#'                   a multi-row header. Default \code{"_"}.
#' @param header_fill How merged header cells are resolved when
#'                   \code{header_rows > 1}: \code{"auto"} (default) reads the
#'                   merged ranges stored in \code{.xlsx}/\code{.xlsm} files and
#'                   falls back to \code{"right"} for \code{.xls};
#'                   \code{"right"} fills upper levels to the right (heuristic,
#'                   no merge information needed); \code{"none"} uses the
#'                   cells as they are.
#' @param file_col   \code{character(1)} or \code{NULL}. Name of the column
#'                   recording the source file (extension stripped) when
#'                   \code{combine = TRUE}. Default \code{"excel_name"};
#'                   \code{NULL} omits the column. Ignored when
#'                   \code{combine = FALSE} (provenance is in the list names).
#' @param sheet_col  \code{character(1)} or \code{NULL}. Name of the column
#'                   recording the source sheet when \code{combine = TRUE}.
#'                   Default \code{"sheet_name"}; \code{NULL} omits it.
#'                   The defaults match \code{export_xlsx()}, so the result
#'                   can be written back to the original layout.
#' @param workers    \code{integer(1)}. Number of parallel processes used to
#'                   read the (file x sheet) tasks. Default \code{1L} (serial).
#'                   Values \code{> 1} open a fork pool on Unix/macOS or a
#'                   PSOCK cluster on Windows; the pool is capped at the number
#'                   of tasks and always shut down on exit. Parallel reading
#'                   pays off when files are large or numerous; for many tiny
#'                   sheets the process / serialization overhead can dominate,
#'                   so leave this at \code{1L} unless the import is heavy.
#' @param verbose    \code{logical(1)}. When \code{TRUE}, print one
#'                   \code{message()} per sheet (source file, sheet name, and
#'                   row x col dimensions, with empty sheets flagged) followed
#'                   by a summary line. Default \code{FALSE}. Output is emitted
#'                   from the master process, so it surfaces identically in
#'                   serial and parallel modes.
#' @param on_error   \code{"stop"} (default) or \code{"warn"}. With
#'                   \code{"stop"}, any file or sheet that cannot be read
#'                   aborts the import with one error listing \emph{all}
#'                   failures. With \code{"warn"}, failed files/sheets are
#'                   skipped and listed in a single warning; the import only
#'                   fails when nothing could be read.
#' @param ...        Additional arguments forwarded to
#'                   \code{\link[readxl]{read_excel}} (e.g. \code{col_types},
#'                   \code{na}, \code{trim_ws}). \strong{Do not} pass
#'                   \code{path}, \code{sheet}, or \code{skip} here; use the
#'                   dedicated parameters above. With \code{header_rows > 1},
#'                   \code{col_names} and \code{range} are set internally and
#'                   must not be passed either; \code{col_types} then refers
#'                   to the data columns.
#'
#' @details
#' \strong{Multi-row headers.} Many hand-made workbooks have a title row and
#' a header spread over several rows with merged cells, e.g.
#' \preformatted{
#' row 1  Growth test records
#' row 2  ID | Breed | Weight (kg)   | Backfat (mm)
#' row 3     |       | Start | End   | P2 | Loin
#' row 4  A001 | Duroc | 28.5 | 102.3 | 11.2 | 56.1
#' }
#' \code{import_xlsx(f, skip = 1, header_rows = 2)} returns the columns
#' \code{ID}, \code{Breed}, \code{Weight (kg)_Start}, \code{Weight (kg)_End},
#' \code{Backfat (mm)_P2}, \code{Backfat (mm)_Loin}. The rules are:
#' \itemize{
#'   \item Merged cells only store their value in their top-left cell. With
#'     \code{header_fill = "auto"} the merged ranges are read from the
#'     workbook itself (\code{<mergeCell>} entries of the sheet XML), and each
#'     range is filled with its value, horizontally and vertically. Header
#'     cells that are genuinely empty stay empty, so a column whose upper
#'     cell is blank gets only its lower label.
#'   \item Without merge information (\code{.xls} files, or
#'     \code{header_fill = "right"}), every level except the last is filled to
#'     the right, restarting wherever a higher level starts a new label.
#'   \item Per column, empty parts and repeated parts (vertically merged
#'     cells) are dropped and the remaining parts joined with
#'     \code{header_sep}; line breaks inside a cell become spaces.
#'   \item Columns without any header become \code{col_<j>}; duplicates are
#'     made unique.
#'   \item The header block is read as text, but the data block is read
#'     separately, so numbers and dates keep their types (reading the whole
#'     sheet as text would turn dates into serial numbers such as
#'     \code{"45296"}).
#'   \item Completely empty data rows (spacer or trailing rows) are dropped.
#' }
#' Labels that are only \emph{visually} spread over several columns with
#' "Center Across Selection" (instead of real merging) are not merges; use
#' \code{header_fill = "right"} for such sheets. Reading the merge
#' information re-scans the sheet XML once, which costs a fraction of the
#' import time and only happens when \code{header_rows > 1}.
#'
#' @return
#' \describe{
#'   \item{\code{combine = TRUE}}{A \code{data.table}. Tracking columns
#'     \code{excel_name} and/or \code{sheet_name} are prepended when their
#'     respective \code{file_col} / \code{sheet_col} are not \code{NULL}.}
#'   \item{\code{combine = FALSE}}{A named \code{list} of \code{data.table}s,
#'     each element named \code{"<filename>_<sheetname>"}. The list carries a
#'     \code{"source_files"} attribute with the original file paths.}
#' }
#'
#' @note
#' Files that share the same base name in different folders cannot be told
#' apart by \code{file_col}; a warning is issued and the labels are made
#' unique, so a later \code{export_xlsx()} round trip does not merge them.
#'
#' @importFrom data.table setDT setcolorder setattr setalloccol getDTthreads
#'   setDTthreads rbindlist `:=`
#' @importFrom readxl read_excel excel_sheets cell_limits
#' @importFrom parallel makeCluster stopCluster parLapply clusterEvalQ mclapply
#' @export
#' @examples
#' # Example: Excel file import demonstrations
#'
#' # Setup test files
#' xlsx_files <- mintyr_example(
#'   mintyr_examples("xlsx_test")    # Get example Excel files
#' )
#'
#' # Example 1: Import and combine all sheets from all files
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   combine = TRUE                  # Combine all sheets into one data.table
#' )
#'
#' # Example 2: Import specific sheets separately
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   combine = FALSE,                 # Keep sheets as separate data.tables
#'   sheet = 2                       # Only import the second sheet
#' )
#'
#' # Example 3: Multi-row header with merged cells and a title row
#' # (row 1 = title, rows 2-3 = header, data from row 4)
#' mh_file <- mintyr_example("multiheader_test.xlsx")
#' import_xlsx(
#'   mh_file,
#'   skip = 1,                       # Skip the title row
#'   header_rows = 2                 # Combine two header rows into one name
#' )
#' # The last column has an empty, unmerged upper cell: it is named "Note".
#' # The heuristic fill would wrongly call it "Backfat (mm)_Note":
#' names(import_xlsx(mh_file, sheet = 1, skip = 1, header_rows = 2,
#'                   header_fill = "right"))
#'
#' # Example 4: Batch import that skips unreadable files instead of stopping
#' bad_file <- tempfile(fileext = ".xlsx")
#' writeLines("not a workbook", bad_file)
#' res <- suppressWarnings(
#'   import_xlsx(c(mh_file, bad_file), skip = 1, header_rows = 2, on_error = "warn")
#' )
#' unique(res$excel_name)
#' unlink(bad_file)
import_xlsx <- function(file,
                        combine   = TRUE,
                        sheet     = NULL,
                        skip      = 0L,
                        header_rows = 1L,
                        header_sep  = "_",
                        header_fill = "auto",
                        file_col  = "excel_name",
                        sheet_col = "sheet_name",
                        workers   = 1L,
                        verbose   = FALSE,
                        on_error  = "stop",
                        ...) {

  # -- 0. Tracking-column arguments ------------------------------------------
  for (nm in c("file_col", "sheet_col")) {
    val <- get(nm)
    if (!is.null(val) && (!is.character(val) || length(val) != 1L || is.na(val) ||
                          !nzchar(val)))
      stop(sprintf("`%s` must be a single non-empty string, or NULL.", nm), call. = FALSE)
  }
  if (!is.null(file_col) && identical(file_col, sheet_col))
    stop("`file_col` and `sheet_col` must differ.", call. = FALSE)

  # -- 1. Input validation ----------------------------------------------------
  if (!is.character(file) || length(file) == 0L || anyNA(file))
    stop("`file` must be a non-empty character vector without NA.", call. = FALSE)
  bad <- file[!file.exists(file)]
  if (length(bad))
    stop("File(s) not found:\n  ", paste(bad, collapse = "\n  "), call. = FALSE)
  .check_flag(combine, "combine")
  if (!is.null(sheet)) {
    if (is.character(sheet)) {
      if (length(sheet) == 0L || anyNA(sheet) || any(!nzchar(sheet)))
        stop("`sheet` names must be non-empty strings.", call. = FALSE)
    } else if (!is.numeric(sheet) || length(sheet) == 0L || anyNA(sheet) ||
               any(sheet < 1) || any(sheet != floor(sheet))) {
      stop("`sheet` must be a positive integer vector, a character vector of ",
           "sheet names, or NULL.", call. = FALSE)
    } else {
      sheet <- as.integer(sheet)
    }
  }
  skip        <- .check_count(skip, "skip", 0L)
  header_rows <- .check_count(header_rows, "header_rows", 1L)
  if (!is.character(header_sep) || length(header_sep) != 1L || is.na(header_sep))
    stop("`header_sep` must be a single character string.", call. = FALSE)
  .check_choice(header_fill, c("auto", "right", "none"), "header_fill")
  .check_choice(on_error, c("stop", "warn"), "on_error")
  .check_flag(verbose, "verbose")
  workers <- .check_count(workers, "workers", 1L)

  dots     <- list(...)
  reserved <- intersect(names(dots), c("path", "sheet", "skip",
                                       if (header_rows > 1L) c("col_names", "range")))
  if (length(reserved))
    stop(sprintf("Do not pass %s via `...`; use the dedicated parameter(s) instead.",
                 paste0("`", reserved, "`", collapse = ", ")), call. = FALSE)

  # -- 2. Restore the data.table thread pool on exit ---------------------------
  old_threads <- data.table::getDTthreads()
  on.exit(data.table::setDTthreads(old_threads), add = TRUE)

  # -- 3. Source labels -------------------------------------------------------
  file_base <- .strip_ext(basename(file))
  if (anyDuplicated(file_base) && (!is.null(file_col) || !combine)) {
    dup <- unique(file_base[duplicated(file_base)])
    warning("Several files share the same base name (", paste(dup, collapse = ", "),
            "). Their rows cannot be told apart by `file_col`, and ",
            "export_xlsx() would merge them into one workbook. Labels were made ",
            "unique with make.unique().", call. = FALSE)
    file_base <- make.unique(file_base, sep = "_")
  }

  # -- 4. Sheet directories: one open per file --------------------------------
  # Files that cannot be opened at all are handled like failed sheets.
  sheets_cache <- lapply(file, function(f) tryCatch(readxl::excel_sheets(f),
    error = function(e) structure(list(message = conditionMessage(e)),
                                  class = "mintyr_read_error")))
  open_failed <- vapply(sheets_cache, inherits, logical(1L), what = "mintyr_read_error")
  file_errors <- vapply(which(open_failed), function(i)
    sprintf("  - %s: %s", file[[i]], sheets_cache[[i]]$message), character(1L))
  if (any(open_failed) && (on_error == "stop" || all(open_failed)))
    stop(sprintf("Failed to open %d of %d file(s):\n", sum(open_failed), length(file)),
         paste(file_errors, collapse = "\n"), call. = FALSE)
  ok_files <- which(!open_failed)

  if (is.numeric(sheet)) {
    min_n <- min(lengths(sheets_cache[ok_files]))
    if (max(sheet) > min_n)
      stop(sprintf("Sheet index %d exceeds the minimum sheet count (%d) across files.",
                   max(sheet), min_n), call. = FALSE)
  } else if (is.character(sheet)) {
    absent <- unlist(lapply(ok_files, function(i) {
      miss <- setdiff(sheet, sheets_cache[[i]])
      if (length(miss)) sprintf("%s: %s", basename(file[[i]]), paste(miss, collapse = ", "))
    }))
    if (length(absent))
      stop("Sheet(s) not found:\n  ", paste(absent, collapse = "\n  "), call. = FALSE)
  }

  # -- 5. Flat (file, sheet) task list ----------------------------------------
  tasks <- unlist(lapply(ok_files, function(i) {
    avail <- sheets_cache[[i]]
    sel   <- if (is.null(sheet)) avail else if (is.character(sheet)) sheet else avail[sheet]
    lapply(sel, function(sht) list(path = file[[i]], base = file_base[[i]], sheet = sht))
  }), recursive = FALSE)

  # -- 6. Read every task (serial or parallel) ---------------------------------
  need_excel <- combine && !is.null(file_col)
  need_sheet <- combine && !is.null(sheet_col)

  read_body <- function(tk) {
    if (header_rows == 1L) {
      raw <- do.call(readxl::read_excel,
                     c(list(path = tk$path, sheet = tk$sheet, skip = skip), dots))
      dt  <- data.table::setDT(raw)
    } else {
      # Multi-row header: the header block is read as text, the data block
      # separately so that readxl still guesses numeric / date types. Both
      # ranges start at column A, which keeps them aligned.
      hdr <- readxl::read_excel(
        tk$path, sheet = tk$sheet, col_names = FALSE, col_types = "text",
        range = readxl::cell_limits(c(skip + 1L, 1L), c(skip + header_rows, NA)),
        .name_repair = "minimal")
      raw <- do.call(readxl::read_excel, c(list(
        path = tk$path, sheet = tk$sheet, col_names = FALSE,
        range = readxl::cell_limits(c(skip + header_rows + 1L, 1L), c(NA, NA)),
        .name_repair = "minimal"), dots))
      # Merged ranges are taken from the workbook itself when possible
      # (.xlsx / .xlsm); .xls files, or a workbook whose XML cannot be
      # parsed, fall back to the right-fill heuristic.
      merges <- NULL
      if (header_fill == "auto" && grepl("\\.xls[xm]$", tk$path, ignore.case = TRUE))
        merges <- tryCatch(xlsx_merges(tk$path, tk$sheet), error = function(e) NULL)
      fill <- if (header_fill == "none") "none" else "right"
      nm <- combine_headers(hdr, header_sep, fill = fill, merges = merges,
                            first_row = skip + 1L)
      dt <- data.table::setDT(raw)
      n  <- ncol(dt)
      if (n == 0L) {
        dt <- data.table::setDT(stats::setNames(rep(list(logical(0L)), length(nm)), nm))
      } else {
        if (length(nm) < n) nm <- make.unique(c(nm, paste0("col_", seq.int(length(nm) + 1L, n))),
                                              sep = header_sep)
        data.table::setnames(dt, nm[seq_len(n)])
        # Rows that are completely empty (spacer rows, trailing blanks) are dropped.
        keep <- Reduce(`|`, lapply(dt, function(x) !is.na(x)))
        if (!all(keep)) dt <- dt[keep]
      }
    }
    if (need_excel) data.table::set(dt, j = file_col,  value = rep(tk$base,  nrow(dt)))
    if (need_sheet) data.table::set(dt, j = sheet_col, value = rep(tk$sheet, nrow(dt)))
    dt
  }
  # Errors are returned as objects instead of thrown, so one bad sheet never
  # aborts a (parallel) batch; they are reported together afterwards.
  read_one <- function(tk) {
    tryCatch(read_body(tk), error = function(e)
      structure(list(message = conditionMessage(e)), class = "mintyr_read_error"))
  }
  # Pure base R helpers, safe to ship to PSOCK workers.
  combine_headers <- .combine_headers
  xlsx_merges     <- .xlsx_merges
  environment(combine_headers) <- environment(xlsx_merges) <- baseenv()
  # Detach read_one from the (large) call frame so PSOCK workers only
  # serialise the few small objects it needs.
  shared <- list2env(
    list(skip = skip, dots = dots, header_rows = header_rows, header_sep = header_sep,
         need_excel = need_excel, need_sheet = need_sheet,
         file_col = file_col, sheet_col = sheet_col,
         header_fill = header_fill, combine_headers = combine_headers,
         xlsx_merges = xlsx_merges),
    parent = globalenv()
  )
  environment(read_body) <- shared
  assign("read_body", read_body, envir = shared)
  environment(read_one) <- shared

  n_tasks     <- length(tasks)
  use_workers <- min(workers, n_tasks)

  if (use_workers > 1L) {
    if (.Platform$OS.type == "windows") {
      cl <- parallel::makeCluster(use_workers)
      on.exit(parallel::stopCluster(cl), add = TRUE)
      parallel::clusterEvalQ(cl, data.table::setDTthreads(1L))
      sheet_tables <- parallel::parLapply(cl, tasks, read_one)
    } else {
      data.table::setDTthreads(1L)          # forked children inherit this
      sheet_tables <- parallel::mclapply(tasks, read_one, mc.cores = use_workers)
      # A killed worker (e.g. out of memory) returns NULL or a try-error.
      sheet_tables <- lapply(sheet_tables, function(x) {
        if (is.data.frame(x) || inherits(x, "mintyr_read_error")) x
        else structure(list(message = if (inherits(x, "try-error")) as.character(x)
                            else "worker returned no result (possibly killed, e.g. out of memory)"),
                       class = "mintyr_read_error")
      })
    }
    # Tables serialised back from workers lose their self-reference.
    # setalloccol() returns the repaired table; it must be re-assigned because
    # its argument here is not a plain symbol.
    if (!combine) sheet_tables <- lapply(sheet_tables, data.table::setalloccol)
  } else {
    sheet_tables <- lapply(tasks, read_one)
  }

  # -- 6b. Failures -------------------------------------------------------------
  failed <- vapply(sheet_tables, inherits, logical(1L), what = "mintyr_read_error")
  if (any(failed) || length(file_errors)) {
    info <- c(file_errors, vapply(which(failed), function(i)
      sprintf("  - %s [sheet '%s']: %s", tasks[[i]]$path, tasks[[i]]$sheet,
              sheet_tables[[i]]$message), character(1L)))
    head_msg <- sprintf("Failed to read %d file(s) / %d of %d sheet(s):\n",
                        length(file_errors), sum(failed), length(failed))
    if (on_error == "stop" || all(failed))
      stop(head_msg, paste(info, collapse = "\n"),
           if (on_error == "warn") "\nNothing could be read.", call. = FALSE)
    warning(head_msg, paste(info, collapse = "\n"), "\nThese were skipped.",
            call. = FALSE)
    sheet_tables <- sheet_tables[!failed]
    tasks        <- tasks[!failed]
  }
  n_tasks <- length(tasks)

  if (verbose) {
    dims <- vapply(sheet_tables, function(d) c(nrow(d), ncol(d)), integer(2L))
    for (i in seq_along(sheet_tables))
      message(sprintf("[%d/%d] '%s' / sheet '%s': %d rows x %d cols%s",
                      i, n_tasks, basename(tasks[[i]]$path), tasks[[i]]$sheet,
                      dims[1L, i], dims[2L, i],
                      if (dims[1L, i] == 0L) "  (empty)" else ""))
    message(sprintf("Imported %d sheet(s) from %d file(s); %d total rows.",
                    n_tasks, length(file), sum(dims[1L, ])))
  }

  # -- 7. Assemble ------------------------------------------------------------
  if (combine) {
    data.table::setDTthreads(old_threads)
    out <- data.table::rbindlist(sheet_tables, use.names = TRUE, fill = TRUE)
    front_cols <- c(if (need_excel) file_col, if (need_sheet) sheet_col)
    front_cols <- intersect(front_cols, names(out))
    if (length(front_cols)) data.table::setcolorder(out, front_cols)
    return(out[])
  }

  nms <- vapply(tasks, function(tk) paste(tk$base, tk$sheet, sep = "_"), character(1L))
  out <- stats::setNames(sheet_tables, make.unique(nms, sep = "_"))
  data.table::setattr(out, "source_files", file)
  out
}
