# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Import Data from XLSX Files
#'
#' @description
#' A high-performance function for importing data from one or multiple Excel
#' files into \code{data.table} format, with fine-grained control over source
#' tracking columns, sheet selection, row skipping, and optional parallel
#' reading across (file, sheet) pairs.
#'
#' Performance characteristics:
#' \itemize{
#'   \item \code{excel_sheets()} called exactly once per file (cached).
#'   \item The real cost of an Excel import is \code{read_excel()} parsing,
#'         which is single-threaded C++ and \emph{not} affected by the
#'         \code{data.table} thread pool. The flat (file x sheet) task list is
#'         therefore read in parallel \strong{across processes} when
#'         \code{workers > 1}: a fork pool on Unix/macOS, a PSOCK cluster on
#'         Windows. The cluster / fork pool is always torn down on exit.
#'   \item \code{setDT()} converts tibbles in-place — zero vector copies.
#'   \item Tracking columns injected via \code{:=} on small per-sheet tables
#'         \emph{before} the single final \code{rbindlist}.
#'   \item The final \code{rbindlist} uses the ambient \code{data.table} thread
#'         pool; tune it globally with \code{\link[data.table]{setDTthreads}} if
#'         needed. Workers are pinned to a single thread during the read phase
#'         so parallel processes do not oversubscribe cores.
#' }
#'
#' @param file       Non-empty \code{character} vector of paths to existing
#'                   \code{.xlsx} / \code{.xls} files.
#' @param rbind      \code{logical(1)}. \code{TRUE} (default) binds all sheets
#'                   into a single \code{data.table}. \code{FALSE} returns a
#'                   flat named list keyed as \code{"<filename>_<sheetname>"}.
#' @param sheet      Positive \code{integer} vector or \code{NULL} (default).
#'                   \code{NULL} imports every sheet. Indices must be valid
#'                   across all supplied files.
#' @param skip       Non-negative \code{integer(1)}. Number of rows to skip
#'                   before reading the header. Forwarded directly to
#'                   \code{\link[readxl]{read_excel}}. Default \code{0L}.
#' @param show_excel_name \code{logical(1)}. When \code{TRUE} (default) and
#'                   \code{rbind = TRUE}, prepends an \code{excel_name} column
#'                   recording the source filename (extension stripped).
#'                   Silently ignored when \code{rbind = FALSE} (provenance is
#'                   already encoded in list-element names).
#' @param show_sheet_name \code{logical(1)}. When \code{TRUE} (default) and
#'                   \code{rbind = TRUE}, prepends a \code{sheet_name} column
#'                   recording the source sheet. Silently ignored when
#'                   \code{rbind = FALSE}.
#' @param workers    \code{integer(1)}. Number of parallel processes used to
#'                   read the (file x sheet) tasks. Default \code{1L} (serial).
#'                   Values \code{> 1} open a fork pool on Unix/macOS or a
#'                   PSOCK cluster on Windows; the pool is capped at the number
#'                   of tasks and always shut down on exit. Parallel reading
#'                   pays off when files are large or numerous; for many tiny
#'                   sheets the process / serialization overhead can dominate,
#'                   so leave this at \code{1L} unless the import is heavy.
#' @param verbose    \code{logical(1)}. When \code{TRUE}, print one
#'                   \code{message()} per sheet (source file, sheet name, and
#'                   row x col dimensions, with empty sheets flagged) followed
#'                   by a summary line. Default \code{FALSE}. Output is emitted
#'                   from the master process, so it surfaces identically in
#'                   serial and parallel modes.
#' @param ...        Additional arguments forwarded to
#'                   \code{\link[readxl]{read_excel}} (e.g. \code{col_types},
#'                   \code{na}, \code{trim_ws}). \strong{Do not} pass
#'                   \code{path}, \code{sheet}, or \code{skip} here; use the
#'                   dedicated parameters above.
#'
#' @return
#' \describe{
#'   \item{\code{rbind = TRUE}}{A \code{data.table}. Tracking columns
#'     \code{excel_name} and/or \code{sheet_name} are prepended when their
#'     respective \code{show_*} flags are \code{TRUE}.}
#'   \item{\code{rbind = FALSE}}{A named \code{list} of \code{data.table}s,
#'     each element named \code{"<filename>_<sheetname>"}. The list carries a
#'     \code{"source_files"} attribute with the original file paths.}
#' }
#'
#' @importFrom data.table setDT setcolorder setattr setalloccol getDTthreads
#'   setDTthreads rbindlist `:=`
#' @importFrom readxl read_excel excel_sheets
#' @importFrom parallel makeCluster stopCluster parLapply clusterEvalQ mclapply
#' @export
#' @examples
#' # Example: Excel file import demonstrations
#'
#' # Setup test files
#' xlsx_files <- mintyr_example(
#'   mintyr_examples("xlsx_test")    # Get example Excel files
#' )
#'
#' # Example 1: Import and combine all sheets from all files
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   rbind = TRUE                    # Combine all sheets into one data.table
#' )
#'
#' # Example 2: Import specific sheets separately
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   rbind = FALSE,                  # Keep sheets as separate data.tables
#'   sheet = 2                       # Only import first sheet
#' )
import_xlsx <- function(file,
                        rbind           = TRUE,
                        sheet           = NULL,
                        skip            = 0L,
                        show_excel_name = TRUE,
                        show_sheet_name = TRUE,
                        workers         = 1L,
                        verbose         = FALSE,
                        ...) {
  excel_name <- sheet_name <- NULL
  
  # ── 1. Input validation ────────────────────────────────────────────────────
  
  # file: non-empty character vector; all paths must exist
  if (!is.character(file) || length(file) == 0L)
    stop("`file` must be a non-empty character vector.", call. = FALSE)
  
  bad <- file[!file.exists(file)]
  if (length(bad))
    stop("File(s) not found:\n  ", paste(bad, collapse = "\n  "), call. = FALSE)
  
  # rbind: single non-NA logical
  if (!is.logical(rbind) || length(rbind) != 1L || is.na(rbind))
    stop("`rbind` must be a single non-NA logical value.", call. = FALSE)
  
  # sheet: NULL or non-empty positive integer vector without NAs
  if (!is.null(sheet)) {
    if (!is.numeric(sheet) || length(sheet) == 0L ||
        anyNA(sheet)        || any(sheet < 1L))
      stop("`sheet` must be a positive integer vector or NULL.", call. = FALSE)
    sheet <- as.integer(sheet)
  }
  
  # skip: single non-negative integer
  if (!is.numeric(skip) || length(skip) != 1L || is.na(skip) || skip < 0L)
    stop("`skip` must be a single non-negative integer.", call. = FALSE)
  skip <- as.integer(skip)
  
  # show_excel_name / show_sheet_name: single non-NA logical each
  for (.p in c("show_excel_name", "show_sheet_name")) {
    v <- get(.p)
    if (!is.logical(v) || length(v) != 1L || is.na(v))
      stop(sprintf("`%s` must be a single non-NA logical.", .p), call. = FALSE)
  }
  
  # workers: single positive integer
  if (!is.numeric(workers) || length(workers) != 1L ||
      is.na(workers)        || workers < 1L)
    stop("`workers` must be a single positive integer.", call. = FALSE)
  workers <- as.integer(workers)
  
  # Guard: path / sheet / skip must not be passed through ...
  reserved <- intersect(names(list(...)), c("path", "sheet", "skip"))
  if (length(reserved))
    stop(sprintf(
      "Do not pass %s via `...`; use the dedicated parameter(s) instead.",
      paste0("`", reserved, "`", collapse = ", ")
    ), call. = FALSE)
  
  # ── 2. Restore the data.table thread pool on exit ─────────────────────────
  #
  # read_excel() is single-threaded and the per-sheet := writes are trivial,
  # so the pool only matters for the final rbindlist, which runs at the user's
  # ambient setting. Workers are pinned to 1 thread during the read phase; we
  # capture the ambient value here and always restore it on exit.
  
  old_threads <- data.table::getDTthreads()
  on.exit(data.table::setDTthreads(old_threads), add = TRUE)
  
  # ── 3. Helper: strip file extension from basename ─────────────────────────
  
  strip_ext <- function(paths) sub("\\.[^.]+$", "", basename(paths))
  
  # ── 4. Cache sheet directories — one file open per file ───────────────────
  
  sheets_cache        <- lapply(file, readxl::excel_sheets)
  names(sheets_cache) <- file
  
  # Validate sheet indices against the smallest sheet count across all files
  if (!is.null(sheet)) {
    min_n <- min(vapply(sheets_cache, length, integer(1L)))
    if (max(sheet) > min_n)
      stop(sprintf(
        "Sheet index %d exceeds the minimum sheet count (%d) across files.",
        max(sheet), min_n), call. = FALSE)
  }
  
  # ── 5. Build flat (file, sheet) task list ─────────────────────────────────
  #
  # Flat iteration over every (file x sheet) pair; avoids nested lapply and
  # keeps the read map in step 6 simple and easy to parallelise.
  
  file_base <- strip_ext(file)
  
  tasks <- unlist(
    lapply(seq_along(file), function(i) {
      avail <- sheets_cache[[ file[[i]] ]]
      sel   <- if (is.null(sheet)) avail else avail[sheet]
      lapply(sel, function(sht)
        list(path = file[[i]], base = file_base[[i]], sheet = sht)
      )
    }),
    recursive = FALSE
  )
  
  # ── 6. Read every (file, sheet) pair (serial or parallel) ─────────────────
  #
  #   • setDT()  — in-place tibble -> data.table, zero vector copies.
  #   • :=       — tracking columns injected by reference on small tables.
  #   • do.call  — only invoked when extra `...` args are present.
  #
  # `need_*`: TRUE when a tracking column will be written (combine mode only).
  
  dots       <- list(...)
  has_dots   <- length(dots) > 0L
  need_excel <- rbind && show_excel_name
  need_sheet <- rbind && show_sheet_name
  
  read_one <- function(tk) {
    
    raw <- if (has_dots) {
      do.call(readxl::read_excel,
              c(list(path = tk$path, sheet = tk$sheet, skip = skip), dots))
    } else {
      readxl::read_excel(tk$path, sheet = tk$sheet, skip = skip)
    }
    
    dt <- data.table::setDT(raw)   # in-place tibble -> data.table, no copy
    
    if (need_excel && need_sheet) {
      dt[, `:=`(excel_name = tk$base, sheet_name = tk$sheet)]
    } else if (need_excel) {
      dt[, excel_name := tk$base]
    } else if (need_sheet) {
      dt[, sheet_name := tk$sheet]
    }
    
    dt
  }
  
  # Detach read_one from the (large) call frame so PSOCK workers only have to
  # serialise the handful of small objects it actually needs.
  environment(read_one) <- list2env(
    list(skip = skip, dots = dots, has_dots = has_dots,
         need_excel = need_excel, need_sheet = need_sheet),
    parent = globalenv()
  )
  
  n_tasks     <- length(tasks)
  use_workers <- min(workers, n_tasks)        # never spawn idle processes
  
  if (use_workers > 1L) {
    
    if (.Platform$OS.type == "windows") {
      # Windows: no fork() — spin up a PSOCK cluster of fresh R sessions.
      cl <- parallel::makeCluster(use_workers)
      on.exit(parallel::stopCluster(cl), add = TRUE)
      # Pin each worker to a single data.table thread (avoid oversubscription).
      parallel::clusterEvalQ(cl, data.table::setDTthreads(1L))
      sheet_tables <- parallel::parLapply(cl, tasks, read_one)
      
    } else {
      # Unix/macOS: fork is cheap and shares memory copy-on-write.
      data.table::setDTthreads(1L)   # forked children inherit this
      sheet_tables <- parallel::mclapply(tasks, read_one, mc.cores = use_workers)
      # mclapply reports a failing task as a try-error rather than stopping.
      failed <- vapply(sheet_tables, inherits, logical(1L), what = "try-error")
      if (any(failed))
        stop("Parallel read failed for ", sum(failed), " task(s). First error:\n  ",
             as.character(sheet_tables[[which(failed)[1L]]]), call. = FALSE)
    }
    
    # Objects serialised back from workers lose their data.table self-reference;
    # restore it cheaply (no data copy) so later by-reference edits are clean.
    if (!rbind)
      for (i in seq_along(sheet_tables))
        data.table::setalloccol(sheet_tables[[i]])
    
  } else {
    sheet_tables <- lapply(tasks, read_one)
  }
  
  # Verbose report, emitted from the master so it shows in serial and parallel
  # modes alike: one line per sheet (dimensions, empty flagged) + a summary.
  if (verbose) {
    dims <- vapply(sheet_tables,
                   function(d) c(nrow(d), ncol(d)), integer(2L))
    for (i in seq_along(sheet_tables)) {
      message(sprintf(
        "[%d/%d] '%s' / sheet '%s': %d rows x %d cols%s",
        i, n_tasks, basename(tasks[[i]]$path), tasks[[i]]$sheet,
        dims[1L, i], dims[2L, i],
        if (dims[1L, i] == 0L) "  (empty)" else ""))
    }
    message(sprintf(
      "Imported %d sheet(s) from %d file(s); %d total rows.",
      n_tasks, length(file), sum(dims[1L, ])))
  }
  
  # ── 7. Assemble output ────────────────────────────────────────────────────
  
  if (rbind) {
    
    # Restore the ambient pool for the bind (the fork path lowered it to 1).
    data.table::setDTthreads(old_threads)
    out <- data.table::rbindlist(sheet_tables, use.names = TRUE, fill = TRUE)
    
    # Move whichever tracking columns were added to the front
    front_cols <- character(0L)
    if (need_excel) front_cols <- c(front_cols, "excel_name")
    if (need_sheet) front_cols <- c(front_cols, "sheet_name")
    if (length(front_cols))
      data.table::setcolorder(out, front_cols)
    
    return(out[])
    
  } else {
    
    # Named list — provenance lives in element names, not extra columns
    nms <- vapply(tasks,
                  function(tk) paste(tk$base, tk$sheet, sep = "_"),
                  character(1L))
    
    out <- stats::setNames(sheet_tables, nms)
    data.table::setattr(out, "source_files", file)
    return(out)
  }
}
