# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Import Data from XLSX Files
#'
#' @description
#' A high-performance function for importing data from one or multiple Excel
#' files into \code{data.table} format, with fine-grained control over source
#' tracking columns, sheet selection, and row skipping.
#'
#' Performance characteristics (v3 baseline, unchanged here):
#' \itemize{
#'   \item \code{excel_sheets()} called exactly once per file (cached).
#'   \item \code{setDT()} converts tibbles in-place — zero vector copies.
#'   \item Tracking columns injected via \code{:=} on small per-sheet tables
#'         \emph{before} the single final \code{rbindlist}.
#'   \item \code{data.table} OpenMP thread pool optionally widened and always
#'         restored on exit.
#' }
#'
#' @param file       Non-empty \code{character} vector of paths to existing
#'                   \code{.xlsx} / \code{.xls} files.
#' @param rbind      \code{logical(1)}. \code{TRUE} (default) binds all sheets
#'                   into a single \code{data.table}. \code{FALSE} returns a
#'                   flat named list keyed as \code{"<filename>_<sheetname>"}.
#' @param sheet      Positive \code{integer} vector or \code{NULL} (default).
#'                   \code{NULL} imports every sheet. Indices must be valid
#'                   across all supplied files.
#' @param skip       Non-negative \code{integer(1)}. Number of rows to skip
#'                   before reading the header. Forwarded directly to
#'                   \code{\link[readxl]{read_excel}}. Default \code{0L}.
#' @param show_excel_name \code{logical(1)}. When \code{TRUE} (default) and
#'                   \code{rbind = TRUE}, prepends an \code{excel_name} column
#'                   recording the source filename (extension stripped).
#'                   Silently ignored when \code{rbind = FALSE} (provenance is
#'                   already encoded in list-element names).
#' @param show_sheet_name \code{logical(1)}. When \code{TRUE} (default) and
#'                   \code{rbind = TRUE}, prepends a \code{sheet_name} column
#'                   recording the source sheet. Silently ignored when
#'                   \code{rbind = FALSE}.
#' @param verbose    \code{logical(1)}. Emit a \code{message()} for every
#'                   empty sheet encountered. Default \code{FALSE}.
#' @param dt_threads \code{integer(1)}. OpenMP threads for \code{data.table}
#'                   operations (\code{rbindlist}, \code{:=}, \code{set*}).
#'                   Defaults to the current \code{getDTthreads()} value.
#'                   Always restored on exit.
#' @param ...        Additional arguments forwarded to
#'                   \code{\link[readxl]{read_excel}} (e.g. \code{col_types},
#'                   \code{na}, \code{trim_ws}). \strong{Do not} pass
#'                   \code{sheet} or \code{skip} here; use the dedicated
#'                   parameters above.
#'
#' @return
#' \describe{
#'   \item{\code{rbind = TRUE}}{A \code{data.table}. Tracking columns
#'     \code{excel_name} and/or \code{sheet_name} are prepended when their
#'     respective \code{show_*} flags are \code{TRUE}.}
#'   \item{\code{rbind = FALSE}}{A named \code{list} of \code{data.table}s,
#'     each element named \code{"<filename>_<sheetname>"}. The list carries a
#'     \code{"source_files"} attribute with the original file paths.}
#' }
#'
#' @importFrom data.table setDT setcolorder setattr getDTthreads setDTthreads
#'   rbindlist `:=`
#' @importFrom readxl read_excel excel_sheets
#' @export
#' @examples
#' # Example: Excel file import demonstrations
#'
#' # Setup test files
#' xlsx_files <- mintyr_example(
#'   mintyr_examples("xlsx_test")    # Get example Excel files
#' )
#'
#' # Example 1: Import and combine all sheets from all files
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   rbind = TRUE                    # Combine all sheets into one data.table
#' )
#'
#' # Example 2: Import specific sheets separately
#' import_xlsx(
#'   xlsx_files,                     # Input Excel file paths
#'   rbind = FALSE,                  # Keep sheets as separate data.tables
#'   sheet = 2                       # Only import first sheet
#' )
import_xlsx <- function(file,
                        rbind           = TRUE,
                        sheet           = NULL,
                        skip            = 0L,
                        show_excel_name = TRUE,
                        show_sheet_name = TRUE,
                        verbose         = FALSE,
                        dt_threads      = data.table::getDTthreads(),
                        ...) {
  excel_name <- sheet_name <- NULL 

  # ── 1. Input validation ────────────────────────────────────────────────────

  # file: non-empty character vector; all paths must exist
  if (!is.character(file) || length(file) == 0L)
    stop("`file` must be a non-empty character vector.", call. = FALSE)

  bad <- file[!file.exists(file)]
  if (length(bad))
    stop("File(s) not found:\n  ", paste(bad, collapse = "\n  "), call. = FALSE)

  # rbind: single non-NA logical
  if (!is.logical(rbind) || length(rbind) != 1L || is.na(rbind))
    stop("`rbind` must be a single non-NA logical value.", call. = FALSE)

  # sheet: NULL or non-empty positive integer vector without NAs
  if (!is.null(sheet)) {
    if (!is.numeric(sheet) || length(sheet) == 0L ||
        anyNA(sheet)        || any(sheet < 1L))
      stop("`sheet` must be a positive integer vector or NULL.", call. = FALSE)
    sheet <- as.integer(sheet)
  }

  # skip: single non-negative integer
  if (!is.numeric(skip) || length(skip) != 1L || is.na(skip) || skip < 0L)
    stop("`skip` must be a single non-negative integer.", call. = FALSE)
  skip <- as.integer(skip)

  # show_excel_name / show_sheet_name: single non-NA logical each
  for (.p in c("show_excel_name", "show_sheet_name")) {
    v <- get(.p)
    if (!is.logical(v) || length(v) != 1L || is.na(v))
      stop(sprintf("`%s` must be a single non-NA logical.", .p), call. = FALSE)
  }

  # dt_threads: single positive integer
  if (!is.numeric(dt_threads) || length(dt_threads) != 1L ||
      is.na(dt_threads)        || dt_threads < 1L)
    stop("`dt_threads` must be a single positive integer.", call. = FALSE)
  dt_threads <- as.integer(dt_threads)

  # Guard: sheet / skip must not be passed through ...
  reserved <- intersect(names(list(...)), c("sheet", "skip"))
  if (length(reserved))
    stop(sprintf(
      "Do not pass %s via `...`; use the dedicated parameter(s) instead.",
      paste0("`", reserved, "`", collapse = " and ")
    ), call. = FALSE)

  # ── 2. Widen data.table thread pool; always restore on exit ───────────────

  old_threads <- data.table::getDTthreads()
  if (dt_threads != old_threads) {
    data.table::setDTthreads(dt_threads)
    on.exit(data.table::setDTthreads(old_threads), add = TRUE)
  }

  # ── 3. Helper: strip file extension from basename ─────────────────────────

  strip_ext <- function(paths) sub("\\.[^.]+$", "", basename(paths))

  # ── 4. Cache sheet directories — one file open per file ───────────────────

  sheets_cache        <- lapply(file, readxl::excel_sheets)
  names(sheets_cache) <- file

  # Validate sheet indices against the smallest sheet count across all files
  if (!is.null(sheet)) {
    min_n <- min(vapply(sheets_cache, length, integer(1L)))
    if (max(sheet) > min_n)
      stop(sprintf(
        "Sheet index %d exceeds the minimum sheet count (%d) across files.",
        max(sheet), min_n), call. = FALSE)
  }

  # ── 5. Build flat (file, sheet) task list ─────────────────────────────────
  #
  # Flat iteration over every (file × sheet) pair; avoids nested lapply and
  # keeps the hot loop in step 6 simple and branch-free.

  file_base <- strip_ext(file)

  tasks <- unlist(
    lapply(seq_along(file), function(i) {
      avail <- sheets_cache[[ file[[i]] ]]
      sel   <- if (is.null(sheet)) avail else avail[sheet]
      lapply(sel, function(sht)
        list(path = file[[i]], base = file_base[[i]], sheet = sht)
      )
    }),
    recursive = FALSE
  )

  # ── 6. Read every (file, sheet) pair ──────────────────────────────────────
  #
  # Micro-optimisations carried over from v3:
  #   • setDT()    — in-place tibble → data.table, zero vector copies.
  #   • :=         — tracking columns injected by reference on small tables.
  #   • do.call    — only invoked when extra `...` args are present.
  #
  # `need_tracking`: TRUE when at least one tracking column will be written.
  # When both show_* flags are FALSE and rbind = TRUE, we skip := entirely.

  dots         <- list(...)
  has_dots     <- length(dots) > 0L
  need_excel   <- rbind && show_excel_name   # only meaningful in combine mode
  need_sheet   <- rbind && show_sheet_name

  sheet_tables <- lapply(tasks, function(tk) {

    # -- Read (skip forwarded explicitly; remaining dots via do.call) ----------
    raw <- if (has_dots) {
      do.call(readxl::read_excel,
              c(list(path = tk$path, sheet = tk$sheet, skip = skip), dots))
    } else {
      readxl::read_excel(tk$path, sheet = tk$sheet, skip = skip)
    }

    # -- In-place tibble → data.table (no vector copy) ------------------------
    dt <- data.table::setDT(raw)

    if (verbose && nrow(dt) == 0L)
      message(sprintf("Note: '%s' / sheet '%s' is empty.",
                      basename(tk$path), tk$sheet))

    # -- Inject only the requested tracking columns by reference --------------
    if (need_excel && need_sheet) {
      dt[, `:=`(excel_name = tk$base, sheet_name = tk$sheet)]
    } else if (need_excel) {
      dt[, excel_name := tk$base]
    } else if (need_sheet) {
      dt[, sheet_name := tk$sheet]
    }

    dt
  })

  # ── 7. Assemble output ────────────────────────────────────────────────────

  if (rbind) {

    out <- data.table::rbindlist(sheet_tables, use.names = TRUE, fill = TRUE)

    # Move whichever tracking columns were added to the front
    front_cols <- character(0L)
    if (need_excel) front_cols <- c(front_cols, "excel_name")
    if (need_sheet) front_cols <- c(front_cols, "sheet_name")
    if (length(front_cols))
      data.table::setcolorder(out, front_cols)

    return(out[])

  } else {

    # Named list — provenance lives in element names, not extra columns
    nms <- vapply(tasks,
                  function(tk) paste(tk$base, tk$sheet, sep = "_"),
                  character(1L))

    out <- stats::setNames(sheet_tables, nms)
    data.table::setattr(out, "source_files", file)
    return(out)
  }
}
