# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Get path to one example
#' 
#' vroom comes bundled with a number of sample files in
#' its 'inst/extdata' directory. Use `vroom_examples()` to list all the
#' available examples.
#' 
#' @param pattern A regular expression of filenames to match. If `NULL`, all available files are returned.
#' @seealso [mintyr::mintyr_example()]
#' @export
#' @examples
#' mintyr_examples()
mintyr_examples <- function (pattern = NULL) {
  list.files(system.file("extdata", package = "mintyr"), pattern = pattern)
}
