# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Apply Cross-Validation to Nested Data Tables
#' 
#' The `nest_cv` function performs cross-validation on nested data tables within a `data.table`. It supports various cross-validation configurations and handles nested lists of data tables.
#' 
#' @param nest_dt data.table. The input data table containing nested data tables.
#' @inheritParams rsample::vfold_cv
#' @return data.table. A data.table with cross-validation splits applied to the nested data tables.
#' 
#' @export
#' 
#' @note
#' \itemize{
#'   \item The `nest_dt` parameter must be a `data.table` containing at least one nested list column of data tables.
#'   \item The function will copy the input `data.table` to avoid modifying the original data.
#' }
#' @examples
#' dt_nest <- w2l_nest(data = iris, cols2l = 1:2, by = "Species")
#' nest_cv(nest_dt = dt_nest, v = 2, repeats = 2)



nest_cv <- function(nest_dt, v = 10, repeats = 1, strata = NULL, breaks = 4, pool = 0.1, ...) {
  cv_split <- data <- splits <- NULL
  # Check if the input nest_dt is a data.table
  if (!inherits(nest_dt, "data.table")) {
    stop("The input nest_dt must be a data.table")
  }

  # Check if nest_dt is not empty
  if (nrow(nest_dt) == 0) {
    stop("The input nest_dt cannot be empty")
  }

  # Check if any column in nest_dt is a nested list of data.tables
  contains_nested_dt <- any(sapply(nest_dt, function(x) is.list(x[[1]]) && all(inherits(x[[1]], "data.table"))))
  if (!contains_nested_dt) {
    stop("The input nest_dt must contain at least one nested list column of data.tables")
  }

  # Copy the input data.table to avoid modifying the original data
  dt <- data.table::copy(nest_dt)

  # Identify which columns are nested lists
  is_nested_list <- sapply(dt, function(x) all(vapply(x, is.list, logical(1))))

  # Get the names of columns that are not nested lists
  non_nested_cols <- names(dt)[!is_nested_list]

  # Apply cross-validation to nested list columns and assign results to cv_split
  dt[, cv_split := purrr::map(data, \(x, ...) rsample::vfold_cv(data = x, ...), ...)
  ][, cv_split[[1]], by = non_nested_cols
  ][, ':='(train = purrr::map(splits, \(x) rsample::training(x)),
           validate = purrr::map(splits, \(x) rsample::testing(x)))][]
}
assert_nest_dt <- function(x) {
  # Check if x is a list and each element is a data.table
  if (!is.list(x)) {
    stop("argument `x` must be a list.")
  }

  # Check if every element of the list is a data.table
  if (!all(sapply(x, inherits, "data.table"))) {
    stop("Each element of `x` must be a data.table.")
  }
}
