# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Row to Pair Nested Transformation
#'
#' @description
#' A flexible data transformation tool for performing row pair conversion 
#' and nesting operations across multiple columns.
#'
#' @param data Input 'data frame' or 'data table'
#'   - Must contain valid columns for transformation
#'   - Supports multiple data types
#'
#' @param rows2bind 'character' or 'numeric' column name/index for row binding
#'   - Specifies target row binding column
#'   - Must be a single column identifier
#'
#' @param by 'character' or 'numeric' column name/index vector
#'   - Columns used for nested pairing
#'   - Must specify at least one column
#'   - Supports multi-column transformation
#'
#' @param nest_type Output nesting format
#'   - `'dt'`: Returns nested 'data table' (default)
#'   - `'df'`: Returns nested 'data frame'
#'
#' @details
#' Advanced Transformation Mechanism:
#' \enumerate{
#'   \item Input validation and preprocessing
#'   \item Dynamic column identification
#'   \item Flexible row pairing across specified columns
#'   \item Nested data structure generation
#' }
#'
#' Transformation Process:
#' \itemize{
#'   \item Convert input to 'data table'
#'   \item Reshape data from wide to long format
#'   \item Perform column-wise nested transformation
#'   \item Support multi-column processing
#' }
#'
#' Index and Column Selection:
#' \itemize{
#'   \item Accepts column names and numeric indices
#'   \item Validates column existence
#'   \item Handles single and multiple column scenarios
#' }
#'
#' @return 'data table' containing nested transformation results
#'   - Includes 'name' column identifying source columns
#'   - Contains 'data' column storing nested data structures
#'
#' @note Key Operation Constraints:
#' \itemize{
#'   \item Requires non-empty input data
#'   \item `by` parameter must specify at least one column
#'   \item Supports flexible column identification
#'   \item Low computational overhead
#' }
#'
#' @seealso
#' \itemize{
#'   \item [`data.table::melt()`] Long format conversion
#'   \item [`data.table::dcast()`] Wide format conversion
#'   \item [`base::rbind()`] Row binding utility
#' }
#'
#' @import data.table
#' @importFrom stats as.formula
#' @export
#' @examples
#' # Sample data
#' data <- data.frame(
#'   breed = c("A", "B", "A", "B"), 
#'   sex = c("F", "F", "M", "M"), 
#'   trait1 = c(1.1, 2.1, 3.5, 4.6),
#'   trait2 = c(5.2, 6.6, 7.3, 8.6))
#' data
#' # Method 1: Using r2p_nest() with data.table
#' # Combine by breed, grouping traits
#' r2p_nest(data, rows2bind = "breed", by = "trait1")
#' # Return as data frame nested structure
#' r2p_nest(data, rows2bind = "breed", by = c("trait1", "trait2"), nest_type = "df")
#' # Method 2: Using tidyr and dplyr for similar transformation
#' data |>
#'   tidyr::pivot_longer(cols = c("trait1"), names_to = "name", values_to = "value") |>
#'   tidyr::pivot_wider(names_from = "breed", values_from = "value") |>
#'   dplyr::group_nest(name)
r2p_nest <- function(data, rows2bind, by, nest_type = "dt") {
  # Input validation
  if (length(by) < 1) {
    stop("At least one column must be specified in 'by'")
  }
  if (length(rows2bind) != 1) {
    stop("rows2bind must be a single column")
  }

  # Convert data to data.table first
  data <- as.data.table(data)

  # Validate column existence and indices
  if (is.numeric(by)) {
    if (any(by > ncol(data) | by < 1)) {
      stop("Invalid column indices in by")
    }
  } else if (!all(by %in% names(data))) {
    stop("Specified by columns not found in data")
  }

  if (is.numeric(rows2bind)) {
    if (rows2bind > ncol(data) | rows2bind < 1) {
      stop("Invalid column index in rows2bind")
    }
  } else if (!rows2bind %in% names(data)) {
    stop("Specified rows2bind not found in data")
  }

  # Process each column in 'by'
  result_list <- lapply(by, function(x) {
    row_pair_init(
      data = data,
      rows2bind = rows2bind,
      by = x,
      nest_type = nest_type
    )
  })

  # Combine all results using rbindlist
  combined_result <- rbindlist(result_list)

  return(combined_result)
}
row_pair_init <- function (data, rows2bind, by, nest_type = "dt") {
  . <- NULL
  # Convert numeric indices to column names
  if (is.numeric(by)) {
    by <- names(data)[by]
  }
  if (is.numeric(rows2bind)) {
    rows2bind <- names(data)[rows2bind]
  }

  # Get ID columns (all columns except 'by' columns)
  id_cols <- setdiff(names(data), by)

  # Reshape data from wide to long format
  long_dt <- melt(data,
                  id.vars = id_cols,
                  measure.vars = by,
                  variable.name = "name",
                  value.name = "value")

  # Get columns for formula creation
  other_ids <- setdiff(id_cols, rows2bind)

  # Create formula string for dcast
  formula_str <- paste(paste(c("name", other_ids), collapse = " + "),
                       rows2bind, sep = " ~ ")

  # Reshape data from long to wide format
  wide_dt <- dcast(long_dt, as.formula(formula_str), value.var = "value")

  # Create nested output based on nest_type
  if (nest_type == "dt") {
    result <- wide_dt[, .(data = list(.SD)), by = "name"]
  }
  else if (nest_type == "df") {
    result <- wide_dt[, .(data = list(as.data.frame(.SD))),
                      by = "name"]
  }
  else {
    stop("Invalid nest_type provided. It must be either 'dt' or 'df'.")
  }

  return(result)
}
