# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Apply Cross-Validation to a List of Datasets
#'
#' @description
#' `split_cv` applies `rsample::vfold_cv` to each dataset in a named or
#' unnamed list, returning a list of `data.table` objects that each contain
#' the CV split objects alongside the corresponding training and validation
#' sets.
#'
#' @param split_dt A `list` whose every element is a `data.frame` or
#'   `data.table`. Must be non-empty.
#' @param v        Number of folds. Must be a single integer >= 2.
#'   Default is `10`.
#' @param repeats  Number of repeats. Must be a single integer >= 1.
#'   Default is `1`.
#' @param strata   A single character string naming the stratification column.
#'   The column must exist in **every** dataset. Set to `NULL` for no
#'   stratification. Default is `NULL`.
#' @param breaks   Number of bins when stratifying a numeric variable. Used
#'   only when `strata` is non-`NULL`. Default is `4`.
#' @param pool     Proportion threshold for pooling small strata. Used only
#'   when `strata` is non-`NULL`. Default is `0.1`.
#' @param ...      Additional arguments forwarded to `rsample::vfold_cv`.
#'
#' @details
#' For each dataset in `split_dt` the function:
#' \enumerate{
#'   \item Validates inputs once before entering the processing loop.
#'   \item Builds a `vfold_cv` argument list, appending stratification
#'         parameters only when `strata` is non-`NULL` to avoid passing
#'         unsupported arguments to `rsample`.
#'   \item Converts the rsample tibble to a `data.table` in a single
#'         `as.data.table()` call, preserving all fold-identifier columns
#'         (`id`, `id2`) without hard-coding on the value of `repeats`.
#'   \item Appends `train` and `validate` list-columns by reference via `:=`.
#' }
#'
#' @return A `list` of `data.table` objects (one per input dataset), each
#'   containing:
#' \itemize{
#'   \item `splits`   — rsample split objects.
#'   \item `id`       — fold identifier (always present).
#'   \item `id2`      — repeat identifier (present only when `repeats > 1`).
#'   \item `train`    — list-column of training data frames.
#'   \item `validate` — list-column of validation data frames.
#' }
#' The output list preserves the names of `split_dt`.
#'
#' @note
#' \itemize{
#'   \item When `strata` is specified, it must exist in **all** datasets;
#'         a missing column raises an error rather than silently falling back
#'         to unstratified CV.
#'   \item `breaks` and `pool` are forwarded to `rsample::vfold_cv` only
#'         when `strata` is non-`NULL`, preventing invalid-argument errors.
#'   \item `as.data.table()` on an already-`data.table` input is a no-op
#'         (no copy is made).
#' }
#'
#' @seealso
#' \itemize{
#'   \item [`rsample::vfold_cv()`]  — underlying cross-validation function
#'   \item [`rsample::training()`]  — extract training set from a split
#'   \item [`rsample::testing()`]   — extract validation set from a split
#'   \item [`nest_cv()`]            — nested data.table variant of this utility
#' }
#'
#' @import data.table
#' @importFrom rsample vfold_cv training testing
#' @export
#' @examples
#' # Prepare example data: Convert first 3 columns of iris dataset to long format and split
#' dt_split <- w2l_split(data = iris, cols2l = 1:3)
#' # dt_split is now a list containing 3 data tables for Sepal.Length, Sepal.Width, and Petal.Length
#'
#' # Example 1: Single cross-validation (no repeats)
#' split_cv(
#'   split_dt = dt_split,  # Input list of split data
#'   v = 3,                # Set 3-fold cross-validation
#'   repeats = 1           # Perform cross-validation once (no repeats)
#' )
#' # Returns a list where each element contains:
#' # - splits: rsample split objects
#' # - id: fold numbers (Fold1, Fold2, Fold3)
#' # - train: training set data
#' # - validate: validation set data
#'
#' # Example 2: Repeated cross-validation
#' split_cv(
#'   split_dt = dt_split,  # Input list of split data
#'   v = 3,                # Set 3-fold cross-validation
#'   repeats = 2           # Perform cross-validation twice
#' )
#' # Returns a list where each element contains:
#' # - splits: rsample split objects
#' # - id: repeat numbers (Repeat1, Repeat2)
#' # - id2: fold numbers (Fold1, Fold2, Fold3)
#' # - train: training set data
#' # - validate: validation set data
split_cv <- function(split_dt,
                     v       = 10L,
                     repeats = 1L,
                     strata  = NULL,
                     breaks  = 4L,
                     pool    = 0.1,
                     ...) {

  # ---------------------------------------------------------------------- #
  #  0. Suppress R CMD CHECK global binding notes
  # ---------------------------------------------------------------------- #
  splits <- train <- validate <- NULL

  # ---------------------------------------------------------------------- #
  #  1. Input validation (performed once, before the processing loop)
  # ---------------------------------------------------------------------- #
  if (!is.list(split_dt)) {
    stop("`split_dt` must be a list. Received: ",
         paste(class(split_dt), collapse = "/"))
  }

  if (length(split_dt) == 0L) {
    stop("`split_dt` must not be empty.")
  }

  if (!is.numeric(v) || length(v) != 1L || v < 2L) {
    stop("`v` must be a single integer >= 2.")
  }

  if (!is.numeric(repeats) || length(repeats) != 1L || repeats < 1L) {
    stop("`repeats` must be a single integer >= 1.")
  }

  # Verify every element inherits from data.frame (covers data.table as well)
  # vapply is preferred over sapply: return type is guaranteed to be logical(1)
  is_valid <- vapply(split_dt, inherits, logical(1L), what = "data.frame")
  if (!all(is_valid)) {
    bad_idx <- which(!is_valid)
    stop("All elements of `split_dt` must be data.frames or data.tables.\n",
         "  Invalid element(s) at index: ", paste(bad_idx, collapse = ", "),
         "\n  Types received: ",
         paste(vapply(split_dt[bad_idx],
                      function(x) class(x)[1L], character(1L)),
               collapse = ", "))
  }

  # Validate strata argument structure and column presence across all datasets
  if (!is.null(strata)) {
    if (!is.character(strata) || length(strata) != 1L) {
      stop("`strata` must be a single character string (column name).")
    }

    # Check column existence in every dataset before entering the loop;
    # failing early avoids partial processing of a multi-dataset list
    strata_missing <- vapply(split_dt, function(df) {
      !strata %in% names(df)
    }, logical(1L))

    if (any(strata_missing)) {
      missing_idx <- which(strata_missing)
      stop("The `strata` column '", strata,
           "' is absent from dataset(s) at index: ",
           paste(missing_idx, collapse = ", "),
           if (!is.null(names(split_dt))) {
             paste0(" (name(s): '",
                    paste(names(split_dt)[missing_idx], collapse = "', '"),
                    "')")
           })
    }
  }

  # ---------------------------------------------------------------------- #
  #  2. Build the vfold_cv argument list once, outside the loop
  #     Strata-specific parameters are appended only when strata is non-NULL,
  #     preventing "unused argument" errors from rsample when strata = NULL
  # ---------------------------------------------------------------------- #
  cv_args <- c(
    list(v = v, repeats = repeats),
    if (!is.null(strata)) list(strata = strata, breaks = breaks, pool = pool),
    list(...)
  )

  # ---------------------------------------------------------------------- #
  #  3. Pre-allocate result list, preserving names from split_dt
  # ---------------------------------------------------------------------- #
  result        <- vector("list", length(split_dt))
  names(result) <- names(split_dt)

  # ---------------------------------------------------------------------- #
  #  4. Process each dataset
  # ---------------------------------------------------------------------- #
  for (i in seq_along(split_dt)) {

    # as.data.table() is a no-op when input is already a data.table;
    # avoids the redundant is.data.table() + conditional branch
    current_data <- data.table::as.data.table(split_dt[[i]])

    # Generate CV splits for this dataset
    cv_obj <- do.call(rsample::vfold_cv, c(list(data = current_data), cv_args))

    # Convert the rsample tibble to data.table in one pass.
    # This naturally retains whichever id columns rsample produced
    # (id only for repeats = 1; both id and id2 for repeats > 1),
    # eliminating the fragile hard-coded `if (repeats == 1)` branch.
    result_dt <- data.table::as.data.table(cv_obj)

    # Append train and validate list-columns by reference (no copy triggered).
    # Pass function references directly instead of wrapping in anonymous lambdas.
    result_dt[, `:=`(
      train    = lapply(splits, rsample::training),
      validate = lapply(splits, rsample::testing)
    )]

    result[[i]] <- result_dt
  }

  result
}
