# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Select Top or Bottom Percentage of Data
#'
#' @description
#' Selects the top (largest) or bottom (smallest) percentage of data based on
#' specified traits. Positive percentages extract the largest values; negative
#' percentages extract the smallest values.
#'
#' @param data A data.frame or data.table.
#' @param perc A numeric vector strictly between -1 and 1 (excluding 0).
#'   Positive values (e.g., 0.05) select the top X% of largest values.
#'   Negative values (e.g., -0.1) select the bottom X% of smallest values.
#' @param trait A character vector of column names to analyse.
#' @param by A character vector of column names to group by. Default is NULL.
#' @param keep_data Logical. If TRUE, returns a named list where each element
#'   contains both \code{stat} (summary statistics) and \code{data} (the
#'   subset rows). If FALSE (default), returns a single combined data.frame of
#'   statistics for all \code{perc} values.
#'
#' @return
#' \itemize{
#'   \item \code{keep_data = FALSE}: a \code{data.frame} with one row per
#'     \code{by} / \code{trait} / \code{perc} combination, containing columns
#'     \code{n, min, max, mean, median, sd, se, cv, selection}.
#'   \item \code{keep_data = TRUE}: a named list (one element per \code{perc}
#'     value) where each element is a list with \code{$stat} and \code{$data}.
#' }
#'
#' @importFrom data.table as.data.table melt frank setkeyv rbindlist
#' @importFrom stats sd median
#' @export
#' @examples
#' # Example 1: Basic usage with single trait
#' # This example selects the top 10% of observations based on Petal.Width
#' # keep_data=TRUE returns both summary statistics and the filtered data
#' top_perc(iris, 
#'          perc = 0.1,                # Select top 10%
#'          trait = c("Petal.Width"),  # Column to analyze
#'          keep_data = TRUE)          # Return both stats and filtered data
#'
#' # Example 2: Using grouping with 'by' parameter
#' # This example performs the same analysis but separately for each Species
#' # Returns nested list with stats and filtered data for each group
#' top_perc(iris, 
#'          perc = 0.1,                # Select top 10%
#'          trait = c("Petal.Width"),  # Column to analyze
#'          by = "Species")            # Group by Species
top_perc <- function(data, perc, trait, by = NULL, keep_data = FALSE) {
  . <- value <- selection <- NULL

  # ------------------------------------------------------------------
  # 1. Argument validation
  # ------------------------------------------------------------------
  missing_args <- character(0)
  if (missing(data))  missing_args <- c(missing_args, "data")
  if (missing(perc))  missing_args <- c(missing_args, "perc")
  if (missing(trait)) missing_args <- c(missing_args, "trait")
  if (length(missing_args) > 0L)
    stop("Missing required argument(s): ", paste(missing_args, collapse = ", "))

  perc <- suppressWarnings(as.numeric(perc))
  if (length(perc) == 0L || anyNA(perc))
    stop("'perc' must be a non-empty numeric vector with no NA values.")
  if (any(perc <= -1 | perc >= 1 | perc == 0))
    stop("Each element of 'perc' must be strictly between -1 and 1, and cannot be 0.")

  if (!is.character(trait) || length(trait) == 0L)
    stop("'trait' must be a non-empty character vector.")

  # ------------------------------------------------------------------
  # 2. Convert to data.table (no unconditional copy — we only read)
  # ------------------------------------------------------------------
  dt <- data.table::as.data.table(data)

  missing_traits <- trait[!trait %in% names(dt)]
  if (length(missing_traits) > 0L)
    stop("Column(s) not found in 'data': ", paste(missing_traits, collapse = ", "))

  if (!is.null(by)) {
    if (!is.character(by) || length(by) == 0L)
      stop("'by' must be a non-empty character vector.")
    missing_by <- by[!by %in% names(dt)]
    if (length(missing_by) > 0L)
      stop("Grouping column(s) not found in 'data': ", paste(missing_by, collapse = ", "))
  }

  # ------------------------------------------------------------------
  # 3. Reshape to long format ONCE, outside the perc loop
  #    na.rm = TRUE: NAs are excluded uniformly before ranking and
  #    statistics, avoiding ambiguity between melt and frank behaviour.
  # ------------------------------------------------------------------
  id_cols <- setdiff(names(dt), trait)

  dt_long <- data.table::melt(
    dt,
    id.vars       = id_cols,
    measure.vars  = trait,
    variable.name = "variable",
    value.name    = "value",
    na.rm         = TRUE       # unified NA exclusion point
  )

  groupby <- if (is.null(by)) "variable" else c(by, "variable")

  # Pre-build a key so subset operations are fast for all perc iterations
  data.table::setkeyv(dt_long, groupby)

  # ------------------------------------------------------------------
  # 4. Iterate over perc values
  # ------------------------------------------------------------------
  results <- lapply(perc, function(p) {

    abs_p <- abs(p)

    # FIX: ranking is computed *within* each group so that .N refers to
    # the group size, not the total table length.  The previous
    # implementation called .I[ranks <= .N * abs_p] in an outer by=
    # clause where .N was the global row count, producing incorrect
    # cut-offs whenever by != NULL.
    idx <- dt_long[
      ,
      .I[{
        r <- if (p > 0L)
          data.table::frank(-value, ties.method = "min", na.last = "keep")
        else
          data.table::frank( value, ties.method = "min", na.last = "keep")
        # na.last = "keep" → NA ranks are NA → NA <= threshold is NA →
        # those rows are not selected (safe, consistent with na.rm = TRUE
        # applied during melt).
        r <= (.N * abs_p)
      }],
      by = groupby
    ]$V1

    sub_dt <- dt_long[idx]

    # Summary statistics per group
    stats_dt <- sub_dt[
      ,
      {
        n_val <- .N
        if (n_val == 0L) {
          .(N      = 0L,
            Min    = NA_real_,
            Max    = NA_real_,
            Mean   = NA_real_,
            Median = NA_real_,
            SD     = NA_real_,
            SE     = NA_real_,
            CV     = NA_real_)
        } else {
          m <- mean(value)
          s <- sd(value)
          .(N      = n_val,
            Min    = min(value),
            Max    = max(value),
            Mean   = m,
            Median = median(value),
            SD     = s,
            SE     = s / sqrt(n_val),
            CV     = s / m)
        }
      },
      by = groupby
    ]

    # FIX: use sprintf to avoid floating-point display artefacts such as
    # 0.1 * 100 → "10.000000000001".  %.4g trims trailing zeros cleanly.
    label <- if (p > 0)
      sprintf("top_%.4g%%",    abs_p * 100)
    else
      sprintf("bottom_%.4g%%", abs_p * 100)

    stats_dt[, selection := label]

    if (keep_data) {
      list(stat = as.data.frame(stats_dt),
           data = as.data.frame(sub_dt))
    } else {
      as.data.frame(stats_dt)
    }
  })

  names(results) <- paste0("perc_", perc)

  # ------------------------------------------------------------------
  # 5. Return
  # ------------------------------------------------------------------
  if (keep_data) {
    return(results)
  } else {
    return(as.data.frame(data.table::rbindlist(results)))
  }
}
