# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand # nolint: line_length_linter.

#' Convert the elements of a split() result to the requested class (internal)
#'
#' @param dt_list    Named list of data.tables produced by split().
#' @param out_type "dt" or "df".
#' @return The same named list with elements of the requested class.
#' @noRd
.convert_split_type <- function(dt_list, out_type) {
  if (out_type == "df") {
    # Elements returned by split() are independent objects, so they can be
    # converted in place with setDF(): no column vector is duplicated.
    dt_list <- lapply(dt_list, data.table::setDF)
  }
  dt_list
}

#' Split a data.table by key columns with names joined by `sep` (internal)
#'
#' @param dt   A data.table.
#' @param keys Character vector of key columns (dropped from each element).
#' @param sep  Separator used to join key values into element names.
#' @return A named list of data.tables.
#' @noRd
.split_named <- function(dt, keys, sep) {
  # `sep =` is only honoured by split.data.table() from data.table 1.16.0 on
  # (older versions silently use "."). Names are therefore built here from
  # each element's own key values, which also guarantees name/content
  # alignment regardless of the data.table version.
  lst <- split(dt, by = keys, keep.by = TRUE, drop = TRUE, sorted = FALSE)
  nms <- vapply(lst, function(x) {
    paste(vapply(keys, function(k) as.character(x[[k]][1L]), character(1L)),
          collapse = sep)
  }, character(1L))
  # Elements are independent objects: drop the key columns by reference.
  lst <- lapply(lst, function(x) data.table::set(x, j = keys, value = NULL))
  names(lst) <- nms
  lst
}

#' Reshape Wide Data to Long Format and Split into a Named List
#'
#' @description
#' `w2l_split` reshapes a wide-format `data.frame` or `data.table` into long
#' format, then splits the result into a named list keyed by the pivoted column
#' identifier (`variable`) and any optional grouping variables supplied via
#' `by`. List element names are derived directly from the grouping key
#' combinations produced by `split()`, guaranteeing name-to-content alignment.
#'
#' @param data `data.frame` or `data.table`. Wide-format input dataset.
#'   The input object is never modified.
#' @param cols `numeric` or `character`. Columns to pivot from wide to long,
#'   specified as integer indices or column names. Default `NULL`: when `NULL`,
#'   `by` must be provided and the function splits the data as-is without
#'   melting.
#' @param by `numeric` or `character`. Additional grouping variables used as
#'   secondary split keys, specified as integer indices or column names.
#'   Default `NULL`.
#' @param out_type `character`. Class of each list element: `"dt"` for
#'   `data.table` (default) or `"df"` for `data.frame`.
#' @param sep `character`. Separator used when concatenating multiple grouping
#'   key values into a single list-element name. Default `"_"`.
#'
#' @return A named list of `data.table` or `data.frame` objects (controlled by
#'   `out_type`). Names reflect the key combination of `variable` (and `by`
#'   levels if provided), joined by `sep`.
#' \itemize{
#'   \item If `by` is `NULL`, the list is keyed by the pivoted column names only.
#'   \item If `by` is specified, the list is keyed by `variable` and all `by`
#'         level combinations.
#' }
#'
#' @details
#' **Name safety:** list names are built from each element's own key values
#' (joined by `sep`), so names always match contents. This also makes `sep`
#' work on every data.table version (`split(sep = )` is only honoured from
#' data.table 1.16.0 on).
#'
#' **Column resolution:** both `cols` and `by` accept integer column
#' positions or character column names. Out-of-bounds indices and unknown names
#' are caught early with informative error messages.
#'
#' **Overlap guard:** columns appearing in both `cols` and `by` raise an
#' error before melting to prevent `id.vars` / `measure.vars` conflicts.
#'
#' **Factor-free melting:** `melt()` is called with `variable.factor = FALSE`
#' so the `variable` column is always `character`, keeping `split()` sort order
#' consistent with lexicographic expectations.
#'
#' **Memory efficiency:** the elements returned by `split()` are independent
#' objects, so for `out_type = "df"` they are converted in place with
#' `setDF()` and no column vector is duplicated. The input itself is never
#' modified.
#'
#' @note
#' \itemize{
#'   \item An empty input table (0 rows) triggers a `warning()` and returns an
#'         empty list immediately.
#'   \item `cols` and `by` must not overlap; shared columns raise an error.
#'   \item `out_type` values other than `"dt"` or `"df"` raise an error.
#' }
#'
#' @seealso `tidytable::group_split()` for a tidyverse-style equivalent.
#'
#' @import data.table
#' @export
#' @examples
#' # Example: Wide to long format splitting demonstrations
#'
#' # Example 1: Basic splitting by Species
#' w2l_split(
#'   data = iris,                    # Input dataset
#'   by = "Species"                  # Split by Species column
#' ) |> 
#'   lapply(head)                    # Show first 6 rows of each split
#'
#' # Example 2: Split specific columns using numeric indices
#' w2l_split(
#'   data = iris,                    # Input dataset
#'   cols = 1:3,                   # Select first 3 columns to split
#'   by = 5                          # Split by column index 5 (Species)
#' ) |> 
#'   lapply(head)                    # Show first 6 rows of each split
#'
#' # Example 3: Split specific columns using column names
#' list_res <- w2l_split(
#'   data = iris,                    # Input dataset
#'   cols = c("Sepal.Length",        # Select columns by name
#'            "Sepal.Width"),
#'   by = "Species"                  # Split by Species column
#' )
#' lapply(list_res, head)            # Show first 6 rows of each split
#' # Returns similar structure to Example 2
w2l_split <- function(data, cols = NULL, by = NULL, out_type = "dt", sep = "_") {

  # -- 1. Input validation ----------------------------------------------------
  if (!is.data.frame(data))
    stop("`data` must be a data.frame or a data.table.", call. = FALSE)
  .check_choice(out_type, c("dt", "df"), "out_type")
  if (!is.character(sep) || length(sep) != 1L || is.na(sep))
    stop("`sep` must be a single character string.", call. = FALSE)

  # Never modify the caller's object (see w2l_nest()).
  dt <- if (data.table::is.data.table(data)) data else data.table::as.data.table(data)
  data_names <- names(dt)

  # -- 2. Resolve columns -----------------------------------------------------
  by <- .resolve_cols(by, data_names, "by", allow_null = TRUE)
  if (is.null(cols)) {
    if (is.null(by))
      stop("When `cols` is NULL, `by` must be provided.", call. = FALSE)
  } else {
    cols  <- .resolve_cols(cols, data_names, "cols")
    overlap <- intersect(cols, by)
    if (length(overlap) > 0L)
      stop("`cols` and `by` share column(s), which would corrupt the melt structure: ",
           paste(overlap, collapse = ", "), call. = FALSE)
    if (any(c("variable", "value") %chin% setdiff(data_names, cols)))
      stop("`data` already contains a column named 'variable' or 'value' that is ",
           "not in `cols`; rename it first.", call. = FALSE)
  }

  # -- 3. Empty input ---------------------------------------------------------
  if (nrow(dt) == 0L) {
    warning("`data` has 0 rows; returning an empty list.", call. = FALSE)
    return(list())
  }

  # -- 4. Split as-is (no melting) --------------------------------------------
  if (is.null(cols)) {
    return(.convert_split_type(.split_named(dt, by, sep), out_type))
  }

  # -- 5. Wide-to-long, then split by variable (+ by) -------------------------
  dt_long <- data.table::melt(
    dt,
    measure.vars    = cols,
    variable.name   = "variable",
    value.name      = "value",
    variable.factor = FALSE
  )
  .convert_split_type(.split_named(dt_long, c("variable", by), sep), out_type)
}
